"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Bot, CheckCircle2, CircleAlert, Loader2, RefreshCw, ThumbsDown, ThumbsUp, Wrench } from "lucide-react";
import { PageHeader } from "@/components/admin/PageHeader";
import { AdminSurface } from "@/components/admin/AdminSurface";
import { fetchJson } from "@/lib/admin/fetchJson";
import { cn } from "@/lib/utils";

type Run = { id: string; surface: string; provider: string | null; model: string | null; tool_pack: string | null; conversation_id: string | null; status: string; tool_names: string[]; input_tokens: number | null; output_tokens: number | null; duration_ms: number | null; result_preview: string | null; error: string | null; started_at: string; finished_at: string | null; feedback: "helpful" | "not_helpful" | null };
type Payload = { schemaReady: boolean; runs: Run[]; feedback: { helpful: number; notHelpful: number } };
function relative(value: string) { const hours = Math.max(0, Math.round((Date.now() - Date.parse(value)) / 3_600_000)); return hours < 1 ? "Just now" : hours < 24 ? `${hours}h ago` : `${Math.ceil(hours / 24)}d ago`; }

export default function AiOperationsPage() {
  const [data, setData] = useState<Payload | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setError(""); try { setData(await fetchJson<Payload>("/api/admin/revenue-os/ai/runs")); } catch (issue) { setError(issue instanceof Error ? issue.message : "Could not load AI operations."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const totals = useMemo(() => ({ runs: data?.runs.length ?? 0, completed: data?.runs.filter((run) => run.status === "completed").length ?? 0, tokens: data?.runs.reduce((sum, run) => sum + Number(run.input_tokens || 0) + Number(run.output_tokens || 0), 0) ?? 0 }), [data]);
  if (loading && !data) return <div className="grid min-h-[55vh] place-items-center"><Loader2 className="size-6 animate-spin text-[var(--admin-muted)]" /></div>;
  return <div className="space-y-7 pb-10"><PageHeader title="AI Operations" subtitle="Inspect bounded copilot runs, tool use, failures, and founder feedback before expanding automation." actions={<button type="button" onClick={() => void load()} className="inline-flex min-h-11 items-center gap-2 rounded-xl px-4 text-xs font-semibold shadow-[var(--admin-shadow-border)] transition-[box-shadow,transform] duration-150 hover:shadow-[var(--admin-shadow-border-hover)] active:scale-[0.96]"><RefreshCw className="size-3.5" />Refresh</button>} />
    {error && <AdminSurface tone="attention"><p className="text-sm text-rose-700 dark:text-rose-300">{error}</p></AdminSurface>}
    {data && <><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Recent runs", value: totals.runs, icon: Bot }, { label: "Completed", value: totals.completed, icon: CheckCircle2 }, { label: "Helpful", value: data.feedback.helpful, icon: ThumbsUp }, { label: "Tokens observed", value: totals.tokens.toLocaleString(), icon: Wrench }].map(({ label, value, icon: Icon }) => <AdminSurface key={label} padding="lg"><div className="flex items-start justify-between"><div><p className="admin-eyebrow">{label}</p><p className="mt-3 text-3xl font-semibold tabular-nums tracking-[-0.045em] text-[var(--admin-ink)]">{value}</p></div><span className="grid size-9 place-items-center rounded-xl bg-black/[0.045] dark:bg-white/[0.06]"><Icon className="size-4" /></span></div></AdminSurface>)}</section>
      <AdminSurface padding="none" className="overflow-hidden"><div className="px-5 py-4 sm:px-6"><p className="admin-eyebrow">Trace ledger</p><h2 className="mt-1 text-balance text-lg font-semibold text-[var(--admin-ink)]">Recent agent decisions</h2><p className="admin-copy mt-1 text-pretty text-xs">Run previews are bounded; secrets and raw tool payloads are intentionally not displayed here.</p></div><div className="divide-y divide-[var(--admin-border)] border-t border-[var(--admin-border)]">{data.runs.map((run) => <div key={run.id} className="px-5 py-4 sm:px-6"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-[var(--admin-ink)]">{run.surface.replace(/_/g, " ")}</p><span className={cn("rounded-full px-2 py-0.5 text-[9px] font-semibold uppercase tracking-[0.08em]", run.status === "completed" ? "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300" : run.status === "failed" ? "bg-rose-500/10 text-rose-700 dark:text-rose-300" : "bg-black/[0.045] text-[var(--admin-muted)] dark:bg-white/[0.06]")}>{run.status}</span>{run.feedback && <span className="inline-flex items-center gap-1 text-[10px] font-semibold text-[var(--admin-muted)]">{run.feedback === "helpful" ? <ThumbsUp className="size-3 text-emerald-600" /> : <ThumbsDown className="size-3 text-rose-600" />}{run.feedback.replace("_", " ")}</span>}</div><p className="admin-copy mt-1 line-clamp-2 text-pretty text-xs">{run.error || run.result_preview || "No response preview recorded."}</p><div className="mt-2 flex flex-wrap gap-1">{[run.provider, run.model, run.tool_pack].filter(Boolean).map((detail) => <span key={detail} className="rounded bg-sky-500/[0.08] px-1.5 py-0.5 font-mono text-[10px] text-sky-700 dark:text-sky-300">{detail}</span>)}{run.tool_names.map((tool) => <span key={tool} className="rounded bg-black/[0.045] px-1.5 py-0.5 font-mono text-[10px] text-[var(--admin-muted)] dark:bg-white/[0.06]">{tool}</span>)}</div></div><div className="shrink-0 text-right text-[10px] font-semibold uppercase tracking-[0.08em] text-[var(--admin-muted)]"><p>{relative(run.started_at)}</p><p className="mt-1 tabular-nums">{Number(run.input_tokens || 0) + Number(run.output_tokens || 0)} tokens</p>{run.duration_ms !== null && <p className="mt-1 tabular-nums">{(run.duration_ms / 1000).toFixed(1)}s</p>}</div></div></div>)}{!data.runs.length && <div className="px-6 py-14 text-center"><CircleAlert className="mx-auto size-5 text-[var(--admin-muted)]" /><p className="mt-3 text-sm font-semibold text-[var(--admin-ink)]">No copilot runs yet</p><p className="admin-copy mt-1 text-xs">Use AI Command from anywhere in admin; every run will appear here.</p></div>}</div></AdminSurface></>}
  </div>;
}
