/** Reviewed installation inventory. Runtime routes are preserved; this list is
 * checked against the marketing route tree so migrations cannot omit a page. */
export const installationRoutes = [
  {
    path: "/[...websitePath]",
    source: "src/app/(marketing)/[...websitePath]/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Published owner-authored pages and collection entries; drafts stay private",
  },
  {
    path: "/about",
    source: "src/app/(marketing)/about/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/blog",
    source: "src/app/(marketing)/blog/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/changelog",
    source: "src/app/(marketing)/changelog/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/command-center/demo",
    source: "src/app/(marketing)/command-center/demo/page.tsx",
    kind: "application",
    collection: null,
    preserve: "Demo redirect",
  },
  {
    path: "/command-center",
    source: "src/app/(marketing)/command-center/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/contact",
    source: "src/app/(marketing)/contact/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/demo/command-center",
    source: "src/app/(marketing)/demo/command-center/page.tsx",
    kind: "application",
    collection: null,
    preserve: "Fictional application demo",
  },
  {
    path: "/docs/[...slug]",
    source: "src/app/(marketing)/docs/[...slug]/page.tsx",
    kind: "collection",
    collection: "docs",
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/docs",
    source: "src/app/(marketing)/docs/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/industries/auto-dealers",
    source: "src/app/(marketing)/industries/auto-dealers/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/industries/home-services",
    source: "src/app/(marketing)/industries/home-services/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/industries/insurance-agencies",
    source: "src/app/(marketing)/industries/insurance-agencies/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/industries/law-firms",
    source: "src/app/(marketing)/industries/law-firms/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/industries/manufacturing",
    source: "src/app/(marketing)/industries/manufacturing/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/industries/medical-dental",
    source: "src/app/(marketing)/industries/medical-dental/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/industries/nonprofits",
    source: "src/app/(marketing)/industries/nonprofits/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/industries",
    source: "src/app/(marketing)/industries/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/industries/professional-services",
    source: "src/app/(marketing)/industries/professional-services/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/industries/real-estate",
    source: "src/app/(marketing)/industries/real-estate/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/industries/startups",
    source: "src/app/(marketing)/industries/startups/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/learn/[slug]",
    source: "src/app/(marketing)/learn/[slug]/page.tsx",
    kind: "collection",
    collection: "articles",
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/learn/category/[category]",
    source: "src/app/(marketing)/learn/category/[category]/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/learn",
    source: "src/app/(marketing)/learn/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/learn/tag/[tag]",
    source: "src/app/(marketing)/learn/tag/[tag]/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/legacy-home",
    source: "src/app/(marketing)/legacy-home/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/open-source",
    source: "src/app/(marketing)/open-source/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/packages",
    source: "src/app/(marketing)/packages/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/",
    source: "src/app/(marketing)/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/partners",
    source: "src/app/(marketing)/partners/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/plan/[token]",
    source: "src/app/(marketing)/plan/[token]/page.tsx",
    kind: "application",
    collection: null,
    preserve: "Private plan review",
  },
  {
    path: "/plan-builder",
    source: "src/app/(marketing)/plan-builder/page.tsx",
    kind: "application",
    collection: null,
    preserve: "Plan configuration and pricing logic",
  },
  {
    path: "/privacy",
    source: "src/app/(marketing)/privacy/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/proposal/[token]",
    source: "src/app/(marketing)/proposal/[token]/page.tsx",
    kind: "application",
    collection: null,
    preserve: "Signed proposal review and acceptance",
  },
  {
    path: "/resources",
    source: "src/app/(marketing)/resources/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/results/[slug]",
    source: "src/app/(marketing)/results/[slug]/page.tsx",
    kind: "collection",
    collection: "results",
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/results",
    source: "src/app/(marketing)/results/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/roadmap",
    source: "src/app/(marketing)/roadmap/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/roofing",
    source: "src/app/(marketing)/roofing/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/services",
    source: "src/app/(marketing)/services/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/style-guide",
    source: "src/app/(marketing)/style-guide/page.tsx",
    kind: "application",
    collection: null,
    preserve: "Developer design reference",
  },
  {
    path: "/team/[slug]",
    source: "src/app/(marketing)/team/[slug]/page.tsx",
    kind: "collection",
    collection: "team",
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/team",
    source: "src/app/(marketing)/team/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/terms",
    source: "src/app/(marketing)/terms/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/work/[slug]",
    source: "src/app/(marketing)/work/[slug]/page.tsx",
    kind: "collection",
    collection: "work",
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
  {
    path: "/work",
    source: "src/app/(marketing)/work/page.tsx",
    kind: "page",
    collection: null,
    preserve: "Existing URL, metadata, content, layout, links and form integrations",
  },
] as const;

export const installationSharedSurfaces = [
  "header",
  "footer",
  "navigation",
  "dock",
  "identity",
  "theme",
  "assets",
  "seo",
] as const;
