"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Activity, Check, ChevronRight, CircleAlert, Clock3, ExternalLink, Filter, Loader2, MessageSquareText, RefreshCw, Search, ShieldCheck, ThumbsDown, ThumbsUp, Wrench } from "lucide-react";
import type { AiRunDetailPayload, AiRunHistoryPayload, AiRunSummary } from "@/lib/revenue-os/ai-operations-contract";
import { AdminSurface } from "./AdminSurface";
import { fetchJson } from "@/lib/admin/fetchJson";
import { cn } from "@/lib/utils";

const statusTone: Record<string, string> = { completed: "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300", partial: "bg-amber-500/10 text-amber-700 dark:text-amber-300", failed: "bg-rose-500/10 text-rose-700 dark:text-rose-300", cancelled: "bg-black/[0.05] text-[var(--admin-muted)] dark:bg-white/[0.06]", running: "bg-sky-500/10 text-sky-700 dark:text-sky-300" };
const toneFor = (status: string) => statusTone[status] || "bg-black/[0.05] text-[var(--admin-muted)] dark:bg-white/[0.06]";
function elapsed(ms: number | null) { if (ms === null) return "—"; return ms < 1000 ? `${ms}ms` : `${(ms / 1000).toFixed(ms < 10_000 ? 1 : 0)}s`; }
function relative(value: string) { const delta = Math.max(0, Date.now() - Date.parse(value)); const minutes = Math.floor(delta / 60_000); if (minutes < 1) return "Just now"; if (minutes < 60) return `${minutes}m ago`; const hours = Math.floor(minutes / 60); return hours < 24 ? `${hours}h ago` : `${Math.floor(hours / 24)}d ago`; }
function title(run: AiRunSummary) { return run.promptPreview || run.resultPreview || run.error || "AI workspace run"; }

function RunRow({ run, active, onSelect }: { run: AiRunSummary; active: boolean; onSelect: () => void }) {
  return <button type="button" onClick={onSelect} className={cn("group flex w-full min-h-[88px] items-start gap-3 px-4 py-4 text-left transition-colors duration-150 sm:px-5", active ? "bg-black/[0.045] dark:bg-white/[0.055]" : "hover:bg-black/[0.025] dark:hover:bg-white/[0.03]")}>
    <span className={cn("mt-0.5 grid size-8 shrink-0 place-items-center rounded-xl", toneFor(run.status))}>{run.status === "completed" ? <Check className="size-3.5" /> : run.status === "running" ? <Loader2 className="size-3.5 animate-spin" /> : <CircleAlert className="size-3.5" />}</span>
    <span className="min-w-0 flex-1"><span className="flex items-center gap-2"><span className="truncate text-sm font-semibold text-[var(--admin-ink)]">{title(run)}</span>{run.feedback === "helpful" ? <ThumbsUp className="size-3 shrink-0 text-emerald-600" /> : run.feedback === "not_helpful" ? <ThumbsDown className="size-3 shrink-0 text-rose-600" /> : null}</span><span className="mt-1 block truncate text-xs text-[var(--admin-muted)]">{run.surface.replace(/_/g, " ")} · {run.toolPack || "core"} · {(run.inputTokens + run.outputTokens).toLocaleString()} tokens</span><span className="mt-2 flex flex-wrap items-center gap-2 text-[10px] font-medium text-[var(--admin-muted)]"><span className={cn("rounded-full px-2 py-0.5 uppercase tracking-[0.07em]", toneFor(run.status))}>{run.status}</span><span>{relative(run.startedAt)}</span><span>{elapsed(run.durationMs)}</span></span></span>
    <ChevronRight className="mt-2 size-4 shrink-0 text-[var(--admin-muted)] transition-transform duration-150 group-hover:translate-x-0.5" />
  </button>;
}

function RunDetail({ id, onConversation }: { id: string; onConversation: (id: string) => void }) {
  const [data, setData] = useState<AiRunDetailPayload | null>(null); const [error, setError] = useState("");
  useEffect(() => { let active = true; void fetchJson<AiRunDetailPayload>(`/api/admin/revenue-os/ai/runs/${encodeURIComponent(id)}`).then((payload) => { if (active) setData(payload); }).catch((issue) => { if (active) setError(issue instanceof Error ? issue.message : "Run details are unavailable."); }); return () => { active = false; }; }, [id]);
  if (error) return <div className="p-6"><CircleAlert className="size-5 text-rose-600" /><p className="mt-3 text-sm font-semibold">Could not load this run</p><p className="admin-copy mt-1 text-xs">{error}</p></div>;
  if (!data) return <div className="grid min-h-72 place-items-center"><Loader2 className="size-5 animate-spin text-[var(--admin-muted)]" /></div>;
  if (!data.run) return <div className="p-6 text-sm text-[var(--admin-muted)]">This run is no longer available.</div>;
  const run = data.run;
  return <div className="min-w-0 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><p className="admin-eyebrow">Run detail</p><h2 className="mt-1 break-words text-balance text-lg font-semibold text-[var(--admin-ink)]">{title(run)}</h2><p className="admin-copy mt-1 text-xs">{new Date(run.startedAt).toLocaleString()} · {run.surface.replace(/_/g, " ")}</p></div><span className={cn("rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.08em]", toneFor(run.status))}>{run.status}</span></div>
    <div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Model", run.model || "Not recorded"], ["Tool pack", run.toolPack || "core"], ["Tokens", (run.inputTokens + run.outputTokens).toLocaleString()], ["Duration", elapsed(run.durationMs)]].map(([label, value]) => <div key={label} className="rounded-xl bg-black/[0.025] p-3 shadow-[var(--admin-shadow-border)] dark:bg-white/[0.035]"><p className="admin-eyebrow">{label}</p><p className="mt-1 truncate text-xs font-semibold tabular-nums text-[var(--admin-ink)]" title={value}>{value}</p></div>)}</div>
    {run.error && <div className="mt-4 rounded-xl bg-rose-500/[0.08] p-3 text-xs text-rose-700 dark:text-rose-300"><CircleAlert className="mr-2 inline size-3.5" />{run.error}</div>}
    {data.degraded && <div className="mt-4 rounded-xl bg-amber-500/[0.09] p-3 text-xs text-amber-800 dark:text-amber-300"><CircleAlert className="mr-2 inline size-3.5" />Some evidence is unavailable: {data.degradationReasons.join("; ")}</div>}
    <div className="mt-6 flex items-center justify-between gap-3"><div className="min-w-0"><p className="admin-eyebrow">Ordered trace</p><p className="admin-copy mt-1 text-xs">Safe summaries only. Inputs and provider payloads stay private.</p></div>{run.conversationId && <button type="button" onClick={() => onConversation(run.conversationId!)} className="inline-flex size-10 shrink-0 items-center justify-center rounded-xl text-xs font-semibold shadow-[var(--admin-shadow-border)] sm:w-auto sm:px-3" aria-label="Open conversation"><MessageSquareText className="size-3.5" /><span className="hidden sm:inline">Open conversation</span></button>}</div>
    <ol className="relative mt-4 space-y-1 before:absolute before:bottom-4 before:left-[15px] before:top-4 before:w-px before:bg-[var(--admin-border)]">{data.events.map((event) => <li key={event.id} className="relative flex gap-3 rounded-xl p-2"><span className={cn("relative z-10 mt-0.5 grid size-8 shrink-0 place-items-center rounded-full bg-[var(--admin-surface)] shadow-[var(--admin-shadow-border)]", event.status === "failed" ? "text-rose-600" : event.status === "completed" ? "text-emerald-600" : "text-[var(--admin-muted)]")}>{event.status === "failed" ? <CircleAlert className="size-3.5" /> : event.toolName ? <Wrench className="size-3.5" /> : <Activity className="size-3.5" />}</span><div className="min-w-0 pt-0.5"><div className="flex flex-wrap items-center gap-x-2"><p className="text-xs font-semibold capitalize text-[var(--admin-ink)]">{event.label}</p><time className="text-[10px] tabular-nums text-[var(--admin-muted)]">{new Date(event.createdAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit", second: "2-digit" })}</time></div><p className="admin-copy mt-0.5 text-xs">{event.summary}</p></div></li>)}</ol>
    {data.eventsTruncated && <p className="mt-3 text-xs font-medium text-amber-800 dark:text-amber-300">This run has more events than this bounded inspector displays.</p>}
    {data.affectedRecords.length > 0 && <div className="mt-5 border-t border-[var(--admin-border)] pt-4"><p className="admin-eyebrow">Linked records</p><div className="mt-2 flex flex-wrap gap-2">{data.affectedRecords.map((record) => <Link key={`${record.type}-${record.id}`} href={record.href} className="inline-flex min-h-10 items-center gap-2 rounded-xl px-3 text-xs font-semibold capitalize shadow-[var(--admin-shadow-border)]">{record.type}<ExternalLink className="size-3" /></Link>)}</div></div>}
  </div>;
}

export function AIRunHistory() {
  const router = useRouter(); const params = useSearchParams();
  const [data, setData] = useState<AiRunHistoryPayload | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState(""); const [windowValue, setWindowValue] = useState("7d"); const [status, setStatus] = useState("all");
  const selected = params.get("run");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const search = new URLSearchParams({ window: windowValue, status, limit: "30" }); if (query.trim()) search.set("q", query.trim()); setData(await fetchJson<AiRunHistoryPayload>(`/api/admin/revenue-os/ai/runs?${search}`)); } catch (issue) { setError(issue instanceof Error ? issue.message : "Run history is unavailable."); } finally { setLoading(false); } }, [query, status, windowValue]);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 180); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { if (!selected && data?.runs[0]) { const next = new URLSearchParams(params.toString()); next.set("run", data.runs[0].id); router.replace(`?${next}`, { scroll: false }); } }, [data, params, router, selected]);
  const select = (id: string) => { const next = new URLSearchParams(params.toString()); next.set("view", "runs"); next.set("run", id); router.replace(`?${next}`, { scroll: false }); };
  const openConversation = (id: string) => { const next = new URLSearchParams(); next.set("conversation", id); router.push(`?${next}`); };
  const metrics = useMemo(() => data ? [{ label: "Runs", value: data.metrics.runs.toLocaleString(), icon: Activity }, { label: "Successful", value: data.metrics.successRate === null ? "—" : `${data.metrics.successRate}%`, icon: ShieldCheck }, { label: "Failures", value: data.metrics.failed.toLocaleString(), icon: CircleAlert }, { label: "Tokens observed", value: data.metrics.totalTokens.toLocaleString(), icon: Wrench }] : [], [data]);
  return <div className="space-y-4">
    {data && <section className="grid grid-cols-2 gap-3 xl:grid-cols-4">{metrics.map(({ label, value, icon: Icon }) => <AdminSurface key={label} padding="md"><div className="flex items-start justify-between gap-2"><div><p className="admin-eyebrow">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums tracking-[-0.04em] text-[var(--admin-ink)] sm:text-3xl">{value}</p></div><span className="grid size-8 place-items-center rounded-xl bg-black/[0.035] dark:bg-white/[0.05]"><Icon className="size-3.5" /></span></div></AdminSurface>)}</section>}
    <AdminSurface padding="sm"><div className="flex flex-col gap-2 lg:flex-row"><label className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[var(--admin-muted)]" /><span className="sr-only">Search runs</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search prompts, outcomes, models, or tools" className="min-h-11 w-full rounded-xl bg-[var(--admin-surface)] pl-10 pr-3 text-sm text-[var(--admin-ink)] shadow-[var(--admin-shadow-border)] outline-none focus:shadow-[var(--admin-shadow-border-hover)]" /></label><div className="grid grid-cols-2 gap-2 sm:flex"><label><span className="sr-only">Time window</span><select value={windowValue} onChange={(event) => setWindowValue(event.target.value)} className="min-h-11 w-full rounded-xl bg-[var(--admin-surface)] px-3 text-xs font-semibold text-[var(--admin-ink)] shadow-[var(--admin-shadow-border)] sm:w-32"><option value="24h">Last 24 hours</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="all">All time</option></select></label><label><span className="sr-only">Status</span><select value={status} onChange={(event) => setStatus(event.target.value)} className="min-h-11 w-full rounded-xl bg-[var(--admin-surface)] px-3 text-xs font-semibold capitalize text-[var(--admin-ink)] shadow-[var(--admin-shadow-border)] sm:w-32"><option value="all">All statuses</option><option value="completed">Completed</option><option value="partial">Partial</option><option value="failed">Failed</option><option value="cancelled">Cancelled</option><option value="running">Running</option></select></label><button type="button" onClick={() => void load()} className="hidden size-11 place-items-center rounded-xl shadow-[var(--admin-shadow-border)] hover:shadow-[var(--admin-shadow-border-hover)] sm:grid" aria-label="Refresh run history"><RefreshCw className={cn("size-3.5", loading && "animate-spin")} /></button></div></div>{data && <div className="mt-2 flex flex-wrap items-center gap-3 px-1 text-[10px] text-[var(--admin-muted)]"><span className="inline-flex items-center gap-1"><Clock3 className="size-3" />Median {elapsed(data.metrics.medianDurationMs)}</span><span>Feedback coverage {data.metrics.feedbackCoverage ?? 0}%</span>{data.summaryTruncated && <span className="inline-flex items-center gap-1 text-amber-700 dark:text-amber-300"><Filter className="size-3" />Summary limited to the latest 500 runs</span>}</div>}</AdminSurface>
    {error && <AdminSurface tone="attention"><CircleAlert className="size-5 text-rose-600" /><p className="mt-3 text-sm font-semibold">Run history could not be loaded</p><p className="admin-copy mt-1 text-xs">{error}</p><button onClick={() => void load()} className="mt-3 min-h-10 rounded-xl px-3 text-xs font-semibold shadow-[var(--admin-shadow-border)]">Try again</button></AdminSurface>}
    {!error && data?.schemaReady === false && <AdminSurface tone="attention"><CircleAlert className="size-5 text-amber-600" /><p className="mt-3 text-sm font-semibold">Run history is not ready</p><p className="admin-copy mt-1 text-xs">Complete the AI runtime setup before inspecting operational traces.</p><Link href="/admin/setup" className="mt-3 inline-flex min-h-10 items-center rounded-xl px-3 text-xs font-semibold shadow-[var(--admin-shadow-border)]">Open Setup Center</Link></AdminSurface>}
    {!error && data?.schemaReady !== false && <AdminSurface padding="none" className="overflow-hidden"><div className="grid min-h-[520px] lg:grid-cols-[minmax(320px,0.92fr)_minmax(0,1.35fr)]"><div className="border-b border-[var(--admin-border)] lg:border-b-0 lg:border-r"><div className="flex items-center justify-between border-b border-[var(--admin-border)] px-5 py-4"><div><p className="admin-eyebrow">Trace ledger</p><p className="mt-1 text-sm font-semibold text-[var(--admin-ink)]">{data?.metrics.runs ?? 0} matching runs</p></div>{loading && <Loader2 className="size-4 animate-spin text-[var(--admin-muted)]" />}</div><div className="divide-y divide-[var(--admin-border)]">{data?.runs.map((run) => <RunRow key={run.id} run={run} active={selected === run.id} onSelect={() => select(run.id)} />)}{!loading && !data?.runs.length && <div className="px-6 py-16 text-center"><Activity className="mx-auto size-5 text-[var(--admin-muted)]" /><p className="mt-3 text-sm font-semibold text-[var(--admin-ink)]">No runs match these filters</p><p className="admin-copy mt-1 text-xs">Try a wider time window or clear the search.</p></div>}</div></div><div className="min-w-0 bg-black/[0.012] dark:bg-white/[0.018]">{selected ? <RunDetail key={selected} id={selected} onConversation={openConversation} /> : <div className="grid min-h-80 place-items-center px-6 text-center"><div><Activity className="mx-auto size-5 text-[var(--admin-muted)]" /><p className="mt-3 text-sm font-semibold text-[var(--admin-ink)]">Select a run to inspect it</p><p className="admin-copy mt-1 text-xs">You will see bounded evidence, timing, and linked records.</p></div></div>}</div></div></AdminSurface>}
  </div>;
}
