export interface DemoScenarioContentProfile {
  supportingPeople: Array<{ name: string; company: string; role: string }>;
  opportunities: Array<{ name: string; value: number; source: string; nextAction: string }>;
  conversations: Array<{ subject: string; intent: string; inbound: string; outbound: string; followUp: string }>;
  tasks: string[];
  actionReasons: string[];
  replyBodies: string[];
  campaignNames: string[];
  contentTitles: string[];
  resourceTitles: string[];
  roadmapTitles: string[];
}

export const SPROUT_PROFILE: DemoScenarioContentProfile = {
  supportingPeople: [
    { name: "Lila Bennett", company: "Bennett Family", role: "Parent / guardian" },
    { name: "Omar Haddad", company: "Haddad Family", role: "Parent / guardian" },
    { name: "Grace Holloway", company: "Holloway Family", role: "Parent / guardian" },
    { name: "Theo Martin", company: "Martin Family", role: "Parent / guardian" },
    { name: "Camila Santos", company: "Santos Family", role: "Parent / guardian" },
    { name: "Jon Bell", company: "Bell Family", role: "Parent / guardian" },
    { name: "Aisha Rahman", company: "Rahman Family", role: "Parent / guardian" },
    { name: "Erin Wallace", company: "Wallace Family", role: "Parent / guardian" },
    { name: "Mateo Silva", company: "Silva Family", role: "Parent / guardian" },
    { name: "Hannah Kim", company: "Kim Family", role: "Parent / guardian" },
    { name: "Isaac Turner", company: "Turner Family", role: "Parent / guardian" },
    { name: "Fatima Noor", company: "Noor Family", role: "Parent / guardian" },
    { name: "Kelly Wu", company: "Wu Family", role: "Parent / guardian" },
    { name: "Javier Mendez", company: "Mendez Family", role: "Parent / guardian" },
    { name: "Sophie Adler", company: "Adler Family", role: "Parent / guardian" },
    { name: "Malcolm Ford", company: "Ford Family", role: "Parent / guardian" },
    { name: "Rina Desai", company: "Desai Family", role: "Parent / guardian" },
    { name: "Ben Crawford", company: "Crawford Family", role: "Parent / guardian" },
    { name: "Talia Brooks", company: "Brooks Family", role: "Parent / guardian" },
    { name: "Noah Jensen", company: "Jensen Family", role: "Parent / guardian" },
    { name: "Mara Evans", company: "Evans Family", role: "Parent / guardian" },
    { name: "Darius King", company: "King Family", role: "Parent / guardian" },
    { name: "Chloe Park", company: "Park Family", role: "Parent / guardian" },
    { name: "Luis Ortega", company: "Ortega Family", role: "Parent / guardian" },
    { name: "Wendy Lawson", company: "Maple Grove PTA", role: "Program coordinator" },
    { name: "Reed Palmer", company: "Lakeview Academy", role: "After-school director" },
    { name: "Monique Hill", company: "Northside Library", role: "Youth services lead" },
    { name: "Elliot Shaw", company: "Riverside Montessori", role: "School administrator" },
  ],
  opportunities: [
    { name: "Tuesday Robotics trial", value: 295, source: "Studio tour", nextAction: "Hold Tuesday trial seat through tomorrow" },
    { name: "Summer Makers Camp enrollment", value: 675, source: "Camp landing page", nextAction: "Send before-care schedule and registration link" },
    { name: "Sibling Art Lab enrollment", value: 520, source: "Parent referral", nextAction: "Confirm sibling rate and age groups" },
    { name: "Oak Street fall enrichment", value: 4800, source: "School partnership", nextAction: "Review the eight-week school proposal" },
    { name: "Saturday Coding Club", value: 360, source: "Open house", nextAction: "Offer the September trial date" },
    { name: "Junior Inventors waitlist", value: 320, source: "Website inquiry", nextAction: "Confirm waitlist position and alternatives" },
    { name: "Winter Break Lab", value: 410, source: "Email newsletter", nextAction: "Send the three-day camp itinerary" },
    { name: "Maple Grove family night", value: 2200, source: "PTA introduction", nextAction: "Confirm room capacity and materials" },
    { name: "Homeschool science cohort", value: 1950, source: "Community partner", nextAction: "Schedule curriculum-fit call" },
    { name: "Riverside after-school pilot", value: 3600, source: "School referral", nextAction: "Share instructor availability" },
    { name: "Birthday build workshop", value: 540, source: "Past family", nextAction: "Confirm guest count and project choice" },
    { name: "Teen design intensive", value: 825, source: "Instagram inquiry", nextAction: "Send portfolio prerequisites" },
    { name: "Friday Art Lab transfer", value: 280, source: "Front desk", nextAction: "Move enrollment without losing credit" },
    { name: "Spring robotics renewal", value: 590, source: "Renewal reminder", nextAction: "Confirm returning-family priority" },
    { name: "Northside Library pop-up", value: 1450, source: "Community outreach", nextAction: "Approve mobile supply list" },
    { name: "School-break caregiver bundle", value: 960, source: "Family email", nextAction: "Draft multi-session option" },
    { name: "Beginner ceramics trial", value: 245, source: "Walk-in", nextAction: "Confirm allergy and apron guidance" },
    { name: "Lakeview Academy STEAM series", value: 5250, source: "Partner referral", nextAction: "Finalize dates with after-school director" },
  ],
  conversations: [
    { subject: "Tuesday robotics trial", intent: "trial_booking", inbound: "We loved the tour and would like to try Tuesday robotics. Is there room next week?", outbound: "There is one trial seat next Tuesday. I can hold it through tomorrow and send the short registration form.", followUp: "Please hold it. I can complete the form tonight." },
    { subject: "Before-care for Makers Camp", intent: "program_question", inbound: "Can you confirm camp hours and whether before-care is available?", outbound: "Camp runs from 9 to 3, and before-care begins at 8. I included the arrival instructions below.", followUp: "Great—before-care makes the week work for us." },
    { subject: "Sibling Art Lab rate", intent: "pricing_question", inbound: "We are considering enrolling both children. Is there a sibling option?", outbound: "Yes. I outlined the sibling rate and the two age-appropriate groups so you can compare them clearly.", followUp: "The groups look right. Can both start the same Saturday?" },
    { subject: "Oak Street enrichment proposal", intent: "partnership_follow_up", inbound: "The principal approved the concept. Could you revise the proposal for eight Thursdays?", outbound: "I updated the series to eight Thursdays and separated instruction, materials, and family showcase costs.", followUp: "That is ready for our purchasing review." },
    { subject: "Junior Inventors waitlist", intent: "availability", inbound: "Do you expect another Junior Inventors section to open?", outbound: "We are evaluating a Wednesday section and I added your family to the priority list.", followUp: "Wednesday would be ideal if it opens." },
    { subject: "Birthday workshop projects", intent: "event_planning", inbound: "Which build projects work best for ten eight-year-olds?", outbound: "The marble maze and light-up creature builds fit that age and guest count best.", followUp: "Let us reserve the light-up creature option." },
    { subject: "Winter Break Lab itinerary", intent: "schedule_question", inbound: "Could you send the day-by-day winter break themes?", outbound: "I attached the robotics, printmaking, and invention-day schedule with pickup notes.", followUp: "Invention day is the one we needed—thank you." },
    { subject: "Homeschool cohort curriculum", intent: "fit_question", inbound: "How much writing is expected in the homeschool science cohort?", outbound: "The cohort is project-led; learners use short lab notes rather than long written assignments.", followUp: "That sounds like a good fit for our group." },
    { subject: "Returning-family priority", intent: "renewal", inbound: "When can current robotics families reserve spring seats?", outbound: "Returning-family priority opens Monday, three days before public registration.", followUp: "Please send our renewal link Monday morning." },
    { subject: "Northside Library supply plan", intent: "partner_logistics", inbound: "Can the pop-up run without sinks in the program room?", outbound: "Yes. I revised the plan to use dry materials and self-contained cleanup kits.", followUp: "Perfect. The room is confirmed for October 12." },
  ],
  tasks: ["Reserve Elena’s Tuesday robotics trial", "Send Marcus the Makers Camp before-care guide", "Confirm sibling start date with Priya", "Revise Oak Street’s eight-week proposal", "Offer Devon the September Coding Club trial", "Update the Junior Inventors priority list", "Send the Winter Break Lab itinerary", "Confirm Maple Grove family-night capacity", "Book the homeschool curriculum-fit call", "Share instructor dates with Riverside Montessori", "Confirm birthday workshop guest count", "Send Teen Design portfolio prerequisites", "Transfer Friday Art Lab credit", "Open returning-family robotics priority", "Approve Northside Library supply list", "Draft the school-break session bundle", "Send ceramics allergy guidance", "Finalize Lakeview Academy series dates"],
  actionReasons: ["A trial seat is available and the family asked for the exact next step.", "The camp question is answered by the published care schedule.", "The sibling-rate request is linked to two age-appropriate groups.", "The school approved the concept and requested a bounded proposal revision.", "A returning family is inside the renewal priority window.", "The community partner confirmed the room and needs the final supply plan."],
  replyBodies: ["Hi Elena,\n\nI’ve held the Tuesday robotics trial through tomorrow. Here is the short registration form and arrival note.\n\nMaya", "Hi Marcus,\n\nBefore-care begins at 8:00 a.m. I included the full camp day and pickup instructions below.\n\nMaya", "Hi Priya,\n\nBoth Saturday groups have space, and the sibling rate is reflected in the enrollment summary.\n\nMaya"],
  campaignNames: ["Returning-family spring priority", "Winter Break Lab enrollment", "School partnership follow-up"],
  contentTitles: ["What a first robotics trial feels like", "A parent’s guide to Makers Camp", "Inside our school enrichment partnerships", "Choosing the right Saturday studio"],
  resourceTitles: ["2026 program calendar", "Camp care and pickup guide", "School partnership overview", "Trial-class preparation checklist"],
  roadmapTitles: ["Family enrollment handoff", "Attendance exception queue", "School roster import", "Returning-family renewal signal", "Camp capacity forecast", "Instructor substitution workflow"],
};

export const NORTHLINE_PROFILE: DemoScenarioContentProfile = {
  supportingPeople: [
    { name: "Bethany Cross", company: "Cross Residence", role: "Homeowner" }, { name: "Caleb Dunn", company: "Dunn Residence", role: "Homeowner" },
    { name: "Rosa Delgado", company: "Delgado Residence", role: "Homeowner" }, { name: "Neil Foster", company: "Foster Residence", role: "Homeowner" },
    { name: "April Gaines", company: "Gaines Residence", role: "Homeowner" }, { name: "Victor Huang", company: "Huang Residence", role: "Homeowner" },
    { name: "Leah Ingram", company: "Ingram Residence", role: "Homeowner" }, { name: "Scott Jarvis", company: "Jarvis Residence", role: "Homeowner" },
    { name: "Marisol Klein", company: "Klein Duplex", role: "Property owner" }, { name: "Derek Long", company: "Long Residence", role: "Homeowner" },
    { name: "Paula McBride", company: "McBride Residence", role: "Homeowner" }, { name: "Gavin Nwosu", company: "Nwosu Residence", role: "Homeowner" },
    { name: "Irene Olson", company: "Olson Residence", role: "Homeowner" }, { name: "Damon Pierce", company: "Pierce Residence", role: "Homeowner" },
    { name: "Nadia Quinn", company: "Quinn Residence", role: "Homeowner" }, { name: "Trevor Russo", company: "Russo Residence", role: "Homeowner" },
    { name: "Alicia Stone", company: "Stone Residence", role: "Homeowner" }, { name: "Kevin Tran", company: "Tran Residence", role: "Homeowner" },
    { name: "Brooke Underwood", company: "Underwood Residence", role: "Homeowner" }, { name: "Wes Vega", company: "Vega Residence", role: "Homeowner" },
    { name: "Yara Wilson", company: "Wilson Residence", role: "Homeowner" }, { name: "Zach Yates", company: "Yates Residence", role: "Homeowner" },
    { name: "Helen Archer", company: "Cedar Court Condominiums", role: "Property manager" }, { name: "Mike Bishop", company: "Bishop Commercial", role: "Facilities director" },
    { name: "Tamara Clay", company: "Willow Ridge HOA", role: "Board president" }, { name: "Frank Dominguez", company: "Dominguez Insurance", role: "Claims adjuster" },
    { name: "Sharon Estes", company: "Estes Realty Group", role: "Broker" }, { name: "Cole Freeman", company: "Freeman Restoration", role: "Referral partner" },
  ],
  opportunities: [
    { name: "Walsh storm restoration", value: 18400, source: "Storm landing page", nextAction: "Confirm Thursday inspection window" }, { name: "Coleman roof replacement", value: 23600, source: "Neighbor referral", nextAction: "Explain ventilation options in estimate" },
    { name: "Moore rental inspection", value: 1450, source: "Property manager", nextAction: "Coordinate tenant access" }, { name: "Ellis hail claim", value: 19750, source: "Insurance referral", nextAction: "Upload the photo report for adjuster" },
    { name: "Lakeview HOA exterior review", value: 8600, source: "HOA board inquiry", nextAction: "Schedule the board walkthrough" }, { name: "Park gutter and fascia", value: 7200, source: "Past customer", nextAction: "Confirm copper color selection" },
    { name: "Cross emergency tarp", value: 1250, source: "After-hours call", nextAction: "Dispatch tarp crew before rain" }, { name: "Dunn architectural shingles", value: 21400, source: "Google Business", nextAction: "Deliver shingle sample board" },
    { name: "Delgado skylight leak", value: 4800, source: "Website inquiry", nextAction: "Inspect flashing and interior moisture" }, { name: "Foster flat-roof repair", value: 9800, source: "Commercial referral", nextAction: "Review core sample results" },
    { name: "Gaines siding replacement", value: 16800, source: "Yard sign", nextAction: "Measure west elevation" }, { name: "Huang chimney flashing", value: 3650, source: "Repeat customer", nextAction: "Confirm masonry coordination" },
    { name: "Ingram insurance supplement", value: 5400, source: "Adjuster introduction", nextAction: "Submit code-upgrade documentation" }, { name: "Jarvis roof tune-up", value: 2100, source: "Maintenance reminder", nextAction: "Book spring maintenance visit" },
    { name: "Cedar Court membrane project", value: 68500, source: "Property portfolio", nextAction: "Present phased access plan" }, { name: "Willow Ridge inspection day", value: 12800, source: "Board referral", nextAction: "Confirm homeowner time blocks" },
    { name: "Bishop Commercial drainage", value: 14900, source: "Facilities network", nextAction: "Map scupper and downspout changes" }, { name: "Estes pre-listing roof report", value: 950, source: "Realtor partner", nextAction: "Deliver report before listing photos" },
  ],
  conversations: [
    { subject: "Inspection after last night’s storm", intent: "inspection_request", inbound: "We found shingles in the yard after the storm. Can someone inspect the roof this week?", outbound: "Yes. I reserved Thursday afternoon and included what our inspector will document.", followUp: "Thursday works. The gate code is in my reply." },
    { subject: "Ventilation line items", intent: "estimate_question", inbound: "We reviewed the estimate and have two questions about the ventilation line items.", outbound: "I separated those items and added a plain-language explanation of each option.", followUp: "The ridge-vent option makes sense. Please keep that one." },
    { subject: "Friday crew start", intent: "production_update", inbound: "Is Friday’s crew start still confirmed?", outbound: "Friday is confirmed. The material delivery is complete and the weather window remains clear.", followUp: "Thanks. We will keep the driveway clear." },
    { subject: "Insurance photo report", intent: "claims_documentation", inbound: "The adjuster needs the slope photos before reviewing our supplement.", outbound: "The labeled slope and collateral-damage photos are organized in the claim packet.", followUp: "I sent the packet link to the adjuster." },
    { subject: "Copper gutter color", intent: "selection", inbound: "Can we see aged copper next to the brick before ordering?", outbound: "I scheduled a sample drop and noted the south-wall brick for comparison.", followUp: "Please leave both samples by the side door." },
    { subject: "Emergency tarp arrival", intent: "urgent_service", inbound: "Water is coming through the guest-room ceiling and rain starts again tonight.", outbound: "The tarp crew is dispatched with an arrival window of 2–4 p.m.", followUp: "The attic access is open and someone will be home." },
    { subject: "Cedar Court access plan", intent: "project_logistics", inbound: "Residents cannot lose both stairwell entrances at the same time.", outbound: "The phased plan keeps one entrance open and gives each building a 48-hour notice.", followUp: "That addresses the board’s main concern." },
    { subject: "Code-upgrade supplement", intent: "insurance_follow_up", inbound: "Did the carrier receive the ice-and-water code documentation?", outbound: "The supplement and municipality excerpt were submitted under the existing claim number.", followUp: "I can see the new document in the carrier portal." },
    { subject: "Spring tune-up timing", intent: "maintenance_booking", inbound: "Can the tune-up happen before the cottonwood season starts?", outbound: "I reserved the April 9 morning window and added gutter clearing.", followUp: "April 9 is perfect." },
    { subject: "Pre-listing roof report", intent: "report_deadline", inbound: "Photography moved up. Can the roof report be ready by Wednesday?", outbound: "The inspection is Tuesday morning and the signed report will be delivered that afternoon.", followUp: "That keeps the listing on schedule." },
  ],
  tasks: ["Confirm the Walsh inspection window", "Send Coleman’s ventilation comparison", "Coordinate Moore tenant access", "Upload Ellis claim photos", "Schedule the Lakeview board walkthrough", "Confirm Park’s gutter color", "Dispatch the Cross tarp crew", "Deliver Dunn’s shingle samples", "Inspect Delgado skylight flashing", "Review Foster core sample results", "Measure the Gaines west elevation", "Confirm Huang masonry coordination", "Submit the Ingram code supplement", "Book the Jarvis spring tune-up", "Present Cedar Court’s access phases", "Confirm Willow Ridge time blocks", "Map Bishop Commercial drainage", "Deliver the Estes pre-listing report"],
  actionReasons: ["Storm damage and a requested inspection window are confirmed.", "The estimate question maps to two documented ventilation options.", "The production start depends on delivered materials and the current weather window.", "The adjuster requested a bounded photo packet tied to the claim.", "Active water intrusion requires the approved emergency-tarp workflow.", "The board’s access constraint is resolved in the revised phase plan."],
  replyBodies: ["Hi Lena,\n\nThursday afternoon is reserved for the storm inspection. We’ll document every slope, flashing detail, and visible collateral hit.\n\nEvan", "Hi Andre,\n\nI separated the ventilation options and highlighted the ridge-vent configuration included in the estimate.\n\nEvan", "Hi Bethany,\n\nThe emergency tarp crew is dispatched for 2–4 p.m. today. Nothing else is required before they arrive.\n\nEvan"],
  campaignNames: ["Storm inspection availability", "Spring roof tune-up", "Realtor report partner update"],
  contentTitles: ["What a storm inspection documents", "Reading a roofing estimate without guesswork", "How production-day access works", "When a roof repair becomes a replacement"],
  resourceTitles: ["Storm damage photo checklist", "Roofing estimate guide", "Production-day preparation sheet", "Warranty and maintenance overview"],
  roadmapTitles: ["Weather hold automation", "Inspection photo packet", "Material delivery exception", "Insurance supplement tracker", "Crew capacity board", "Warranty registration receipt"],
};

export const HARBORLINE_PROFILE: DemoScenarioContentProfile = {
  supportingPeople: [
    { name: "Amelia Boyd", company: "Crescent Foods", role: "VP Marketing" }, { name: "Nathan Cho", company: "Crescent Foods", role: "Finance director" },
    { name: "Bianca Flores", company: "Lumen Health", role: "Chief operating officer" }, { name: "Connor Hale", company: "Lumen Health", role: "Growth lead" },
    { name: "Mei Ito", company: "Fieldstone Capital", role: "Managing director" }, { name: "Dylan James", company: "Fieldstone Capital", role: "Principal" },
    { name: "Kira Lowell", company: "Juniper Works", role: "Founder" }, { name: "Elias Moss", company: "Juniper Works", role: "Head of sales" },
    { name: "Anika Nair", company: "Aperture Learning", role: "Chief executive officer" }, { name: "Peter Owens", company: "Aperture Learning", role: "Marketing director" },
    { name: "Celeste Price", company: "Meridian Bio", role: "Commercial director" }, { name: "Rohan Sethi", company: "Meridian Bio", role: "Product marketing lead" },
    { name: "Tessa Vaughn", company: "Vaughn Advisory", role: "Managing partner" }, { name: "Ian Webb", company: "Vaughn Advisory", role: "Operations manager" },
    { name: "Mina Xu", company: "Northstar Robotics", role: "Chief of staff" }, { name: "Aaron Young", company: "Northstar Robotics", role: "Revenue lead" },
    { name: "Zoe Alvarez", company: "Commonwell", role: "Founder" }, { name: "Blake Conrad", company: "Commonwell", role: "Head of partnerships" },
    { name: "Nora Dyer", company: "Redwood Legal", role: "Practice director" }, { name: "Sanjay Iyer", company: "Redwood Legal", role: "Managing partner" },
    { name: "Elise Jordan", company: "Fable Commerce", role: "VP Ecommerce" }, { name: "Martin Ko", company: "Fable Commerce", role: "Analytics lead" },
    { name: "Ava Larson", company: "Beacon Climate", role: "Co-founder" }, { name: "George Malik", company: "Beacon Climate", role: "Commercial lead" },
    { name: "Renee Novak", company: "Novak Ventures", role: "Operating partner" }, { name: "Sam Osei", company: "Osei Product Studio", role: "Founder" },
    { name: "Clara Penn", company: "Penn Executive Search", role: "President" }, { name: "Henry Ruiz", company: "Atlas Manufacturing", role: "Strategy director" },
  ],
  opportunities: [
    { name: "Northwind conversion rebuild", value: 48000, source: "Website assessment", nextAction: "Review the two highest-impact conversion gaps" }, { name: "Whitfield growth operations retainer", value: 72000, source: "Partner referral", nextAction: "Separate reporting from the operating scope" },
    { name: "Brightwater demand program", value: 58500, source: "Founder introduction", nextAction: "Confirm discovery stakeholders" }, { name: "Atwell referral campaign", value: 26000, source: "Existing client", nextAction: "Approve the exclusion list" },
    { name: "Halcyon client reporting system", value: 36000, source: "Quarterly review", nextAction: "Map partner reporting decisions" }, { name: "Crescent category launch", value: 64000, source: "Executive referral", nextAction: "Align finance and marketing success measures" },
    { name: "Lumen lifecycle redesign", value: 52000, source: "Website inquiry", nextAction: "Audit handoff between sales and onboarding" }, { name: "Fieldstone portfolio narrative", value: 44000, source: "Conference conversation", nextAction: "Select three portfolio proof points" },
    { name: "Juniper sales operating system", value: 81000, source: "Founder network", nextAction: "Review pipeline governance gaps" }, { name: "Aperture enrollment campaign", value: 39500, source: "Content referral", nextAction: "Confirm audience and offer constraints" },
    { name: "Meridian launch research", value: 33000, source: "Product leader referral", nextAction: "Approve interview cohort" }, { name: "Vaughn advisory repositioning", value: 42000, source: "Past collaborator", nextAction: "Choose decision-maker interview dates" },
    { name: "Northstar revenue narrative", value: 55000, source: "Board introduction", nextAction: "Reconcile product and sales language" }, { name: "Commonwell partnership engine", value: 47000, source: "Partner inquiry", nextAction: "Score the first partner cohort" },
    { name: "Redwood practice growth plan", value: 68000, source: "Managing partner referral", nextAction: "Review conflict-safe outreach" }, { name: "Fable retention analytics", value: 61000, source: "Analytics assessment", nextAction: "Validate the churn cohort definition" },
    { name: "Beacon commercial launch", value: 75000, source: "Investor introduction", nextAction: "Confirm launch decision rights" }, { name: "Atlas channel strategy", value: 57000, source: "Executive search partner", nextAction: "Schedule distributor interviews" },
  ],
  conversations: [
    { subject: "Website assessment priorities", intent: "discovery_request", inbound: "The assessment was helpful. Can we talk through the two highest-priority conversion issues?", outbound: "Absolutely. I linked each recommendation to the evidence and proposed a focused 30-minute review.", followUp: "Tuesday morning works for our operations and marketing leads." },
    { subject: "Revised scope structure", intent: "proposal_revision", inbound: "Please separate reporting from the main scope so finance can review it independently.", outbound: "Done. Reporting is now its own line with timing, ownership, and acceptance criteria.", followUp: "Finance has the revised version for Friday review." },
    { subject: "Campaign exclusion list", intent: "campaign_approval", inbound: "The campaign draft looks right. Can you confirm the exclusion list before launch?", outbound: "Confirmed. Existing clients, prior replies, and suppressed contacts are excluded in the dry run.", followUp: "Approved from our side once the dry-run count is attached." },
    { subject: "Discovery stakeholder map", intent: "stakeholder_alignment", inbound: "Should finance join the first Brightwater discovery session?", outbound: "Finance is most useful in session two, after we map the current demand and handoff model.", followUp: "That sequencing works. I will invite operations first." },
    { subject: "Partner reporting decisions", intent: "reporting_design", inbound: "The partners want fewer charts and clearer decisions in the monthly report.", outbound: "I reduced the report to pipeline movement, client risk, delivery capacity, and three decisions.", followUp: "This is much closer to how the meeting actually runs." },
    { subject: "Category launch measures", intent: "success_metrics", inbound: "Marketing and finance are using different definitions of launch success.", outbound: "I drafted one shared scorecard separating leading demand, conversion, and recognized revenue.", followUp: "Please use that structure in Thursday’s alignment session." },
    { subject: "Sales-to-onboarding handoff", intent: "operations_audit", inbound: "Clients repeat the same information after contracts are signed.", outbound: "The audit found three fields that can move directly from opportunity to onboarding.", followUp: "Let’s prioritize the handoff before changing nurture." },
    { subject: "Portfolio proof points", intent: "narrative_review", inbound: "We need proof points that work for operators, not just investors.", outbound: "I selected three examples with measurable operating change and named source evidence.", followUp: "The second example will resonate most with our operating partners." },
    { subject: "Interview cohort approval", intent: "research_approval", inbound: "Does the research cohort include both current and lost opportunities?", outbound: "Yes—six current buyers, four lost evaluations, and two channel partners, with no overlap.", followUp: "Approved. Recruiting can start Monday." },
    { subject: "Distributor interview schedule", intent: "scheduling", inbound: "Two distributors can meet next week, but only before 9 a.m.", outbound: "I held Tuesday and Thursday at 8:30 and attached the interview frame.", followUp: "Keep both holds; I will confirm names tomorrow." },
  ],
  tasks: ["Schedule Northwind’s conversion review", "Send Whitfield’s separated reporting scope", "Confirm Brightwater discovery stakeholders", "Attach Atwell’s campaign dry-run count", "Map Halcyon partner decisions", "Align Crescent launch measures", "Audit Lumen’s onboarding handoff", "Select Fieldstone proof points", "Review Juniper pipeline governance", "Confirm Aperture audience constraints", "Approve Meridian interview cohort", "Book Vaughn decision-maker interviews", "Reconcile Northstar revenue language", "Score Commonwell’s partner cohort", "Review Redwood conflict-safe outreach", "Validate Fable churn cohorts", "Confirm Beacon launch decision rights", "Schedule Atlas distributor interviews"],
  actionReasons: ["The assessment evidence identifies two bounded conversion priorities.", "Finance requested a separable reporting decision with explicit acceptance criteria.", "The campaign is ready only after exclusions and dry-run counts reconcile.", "Discovery sequencing depends on a confirmed stakeholder map.", "Partners asked for a decision-oriented reporting structure.", "The research cohort is approved and ready for bounded recruiting."],
  replyBodies: ["Hi Sarah,\n\nI linked the two highest-impact conversion issues to their evidence and held Tuesday morning for a focused review.\n\nAvery", "Hi Dana,\n\nReporting is now a separate scope line with timing, ownership, and acceptance criteria for finance.\n\nAvery", "Hi Ray,\n\nThe dry run excludes existing clients, prior replies, and suppressed contacts. I attached the reconciled audience count.\n\nAvery"],
  campaignNames: ["Website assessment follow-up", "Decision-maker research invitation", "Referral partner reactivation"],
  contentTitles: ["The operating cost of unclear handoffs", "How to turn an assessment into a decision", "A practical revenue-operations scorecard", "What evidence belongs in a proposal"],
  resourceTitles: ["Website assessment brief", "Discovery stakeholder map", "Campaign approval checklist", "Monthly operating review template"],
  roadmapTitles: ["Assessment-to-opportunity handoff", "Proposal evidence pack", "Decision-maker context sheet", "Campaign exclusion audit", "Client reporting decision log", "Referral attribution model"],
};
