export interface DemoScenarioContentProfile {
  supportingPeople: Array<{ name: string; company: string; role: string }>;
  opportunities: Array<{ name: string; value: number; source: string; nextAction: string }>;
  conversations: Array<{ subject: string; intent: string; inbound: string; outbound: string; followUp: string }>;
  tasks: string[];
  actionReasons: string[];
  replyBodies: string[];
  campaignNames: string[];
  contentTitles: string[];
  resourceTitles: string[];
  roadmapTitles: string[];
}

export const SPROUT_PROFILE: DemoScenarioContentProfile = {
  supportingPeople: [
    { name: "Lila Bennett", company: "Bennett Family", role: "Parent / guardian" },
    { name: "Omar Haddad", company: "Haddad Family", role: "Parent / guardian" },
    { name: "Grace Holloway", company: "Holloway Family", role: "Parent / guardian" },
    { name: "Theo Martin", company: "Martin Family", role: "Parent / guardian" },
    { name: "Camila Santos", company: "Santos Family", role: "Parent / guardian" },
    { name: "Jon Bell", company: "Bell Family", role: "Parent / guardian" },
    { name: "Aisha Rahman", company: "Rahman Family", role: "Parent / guardian" },
    { name: "Erin Wallace", company: "Wallace Family", role: "Parent / guardian" },
    { name: "Mateo Silva", company: "Silva Family", role: "Parent / guardian" },
    { name: "Hannah Kim", company: "Kim Family", role: "Parent / guardian" },
    { name: "Isaac Turner", company: "Turner Family", role: "Parent / guardian" },
    { name: "Fatima Noor", company: "Noor Family", role: "Parent / guardian" },
    { name: "Kelly Wu", company: "Wu Family", role: "Parent / guardian" },
    { name: "Javier Mendez", company: "Mendez Family", role: "Parent / guardian" },
    { name: "Sophie Adler", company: "Adler Family", role: "Parent / guardian" },
    { name: "Malcolm Ford", company: "Ford Family", role: "Parent / guardian" },
    { name: "Rina Desai", company: "Desai Family", role: "Parent / guardian" },
    { name: "Ben Crawford", company: "Crawford Family", role: "Parent / guardian" },
    { name: "Talia Brooks", company: "Brooks Family", role: "Parent / guardian" },
    { name: "Noah Jensen", company: "Jensen Family", role: "Parent / guardian" },
    { name: "Mara Evans", company: "Evans Family", role: "Parent / guardian" },
    { name: "Darius King", company: "King Family", role: "Parent / guardian" },
    { name: "Chloe Park", company: "Park Family", role: "Parent / guardian" },
    { name: "Luis Ortega", company: "Ortega Family", role: "Parent / guardian" },
    { name: "Wendy Lawson", company: "Maple Grove PTA", role: "Program coordinator" },
    { name: "Reed Palmer", company: "Lakeview Academy", role: "After-school director" },
    { name: "Monique Hill", company: "Northside Library", role: "Youth services lead" },
    { name: "Elliot Shaw", company: "Riverside Montessori", role: "School administrator" },
  ],
  opportunities: [
    { name: "Tuesday Robotics trial", value: 295, source: "Studio tour", nextAction: "Hold Tuesday trial seat through tomorrow" },
    { name: "Summer Makers Camp enrollment", value: 675, source: "Camp landing page", nextAction: "Send before-care schedule and registration link" },
    { name: "Sibling Art Lab enrollment", value: 520, source: "Parent referral", nextAction: "Confirm sibling rate and age groups" },
    { name: "Oak Street fall enrichment", value: 4800, source: "School partnership", nextAction: "Review the eight-week school proposal" },
    { name: "Saturday Coding Club", value: 360, source: "Open house", nextAction: "Offer the September trial date" },
    { name: "Junior Inventors waitlist", value: 320, source: "Website inquiry", nextAction: "Confirm waitlist position and alternatives" },
    { name: "Winter Break Lab", value: 410, source: "Email newsletter", nextAction: "Send the three-day camp itinerary" },
    { name: "Maple Grove family night", value: 2200, source: "PTA introduction", nextAction: "Confirm room capacity and materials" },
    { name: "Homeschool science cohort", value: 1950, source: "Community partner", nextAction: "Schedule curriculum-fit call" },
    { name: "Riverside after-school pilot", value: 3600, source: "School referral", nextAction: "Share instructor availability" },
    { name: "Birthday build workshop", value: 540, source: "Past family", nextAction: "Confirm guest count and project choice" },
    { name: "Teen design intensive", value: 825, source: "Instagram inquiry", nextAction: "Send portfolio prerequisites" },
    { name: "Friday Art Lab transfer", value: 280, source: "Front desk", nextAction: "Move enrollment without losing credit" },
    { name: "Spring robotics renewal", value: 590, source: "Renewal reminder", nextAction: "Confirm returning-family priority" },
    { name: "Northside Library pop-up", value: 1450, source: "Community outreach", nextAction: "Approve mobile supply list" },
    { name: "School-break caregiver bundle", value: 960, source: "Family email", nextAction: "Draft multi-session option" },
    { name: "Beginner ceramics trial", value: 245, source: "Walk-in", nextAction: "Confirm allergy and apron guidance" },
    { name: "Lakeview Academy STEAM series", value: 5250, source: "Partner referral", nextAction: "Finalize dates with after-school director" },
  ],
  conversations: [
    { subject: "Tuesday robotics trial", intent: "trial_booking", inbound: "We loved the tour and would like to try Tuesday robotics. Is there room next week?", outbound: "There is one trial seat next Tuesday. I can hold it through tomorrow and send the short registration form.", followUp: "Please hold it. I can complete the form tonight." },
    { subject: "Before-care for Makers Camp", intent: "program_question", inbound: "Can you confirm camp hours and whether before-care is available?", outbound: "Camp runs from 9 to 3, and before-care begins at 8. I included the arrival instructions below.", followUp: "Great—before-care makes the week work for us." },
    { subject: "Sibling Art Lab rate", intent: "pricing_question", inbound: "We are considering enrolling both children. Is there a sibling option?", outbound: "Yes. I outlined the sibling rate and the two age-appropriate groups so you can compare them clearly.", followUp: "The groups look right. Can both start the same Saturday?" },
    { subject: "Oak Street enrichment proposal", intent: "partnership_follow_up", inbound: "The principal approved the concept. Could you revise the proposal for eight Thursdays?", outbound: "I updated the series to eight Thursdays and separated instruction, materials, and family showcase costs.", followUp: "That is ready for our purchasing review." },
    { subject: "Junior Inventors waitlist", intent: "availability", inbound: "Do you expect another Junior Inventors section to open?", outbound: "We are evaluating a Wednesday section and I added your family to the priority list.", followUp: "Wednesday would be ideal if it opens." },
    { subject: "Birthday workshop projects", intent: "event_planning", inbound: "Which build projects work best for ten eight-year-olds?", outbound: "The marble maze and light-up creature builds fit that age and guest count best.", followUp: "Let us reserve the light-up creature option." },
    { subject: "Winter Break Lab itinerary", intent: "schedule_question", inbound: "Could you send the day-by-day winter break themes?", outbound: "I attached the robotics, printmaking, and invention-day schedule with pickup notes.", followUp: "Invention day is the one we needed—thank you." },
    { subject: "Homeschool cohort curriculum", intent: "fit_question", inbound: "How much writing is expected in the homeschool science cohort?", outbound: "The cohort is project-led; learners use short lab notes rather than long written assignments.", followUp: "That sounds like a good fit for our group." },
    { subject: "Returning-family priority", intent: "renewal", inbound: "When can current robotics families reserve spring seats?", outbound: "Returning-family priority opens Monday, three days before public registration.", followUp: "Please send our renewal link Monday morning." },
    { subject: "Northside Library supply plan", intent: "partner_logistics", inbound: "Can the pop-up run without sinks in the program room?", outbound: "Yes. I revised the plan to use dry materials and self-contained cleanup kits.", followUp: "Perfect. The room is confirmed for October 12." },
  ],
  tasks: ["Reserve Elena’s Tuesday robotics trial", "Send Marcus the Makers Camp before-care guide", "Confirm sibling start date with Priya", "Revise Oak Street’s eight-week proposal", "Offer Devon the September Coding Club trial", "Update the Junior Inventors priority list", "Send the Winter Break Lab itinerary", "Confirm Maple Grove family-night capacity", "Book the homeschool curriculum-fit call", "Share instructor dates with Riverside Montessori", "Confirm birthday workshop guest count", "Send Teen Design portfolio prerequisites", "Transfer Friday Art Lab credit", "Open returning-family robotics priority", "Approve Northside Library supply list", "Draft the school-break session bundle", "Send ceramics allergy guidance", "Finalize Lakeview Academy series dates"],
  actionReasons: ["A trial seat is available and the family asked for the exact next step.", "The camp question is answered by the published care schedule.", "The sibling-rate request is linked to two age-appropriate groups.", "The school approved the concept and requested a bounded proposal revision.", "A returning family is inside the renewal priority window.", "The community partner confirmed the room and needs the final supply plan."],
  replyBodies: ["Hi Elena,\n\nI’ve held the Tuesday robotics trial through tomorrow. Here is the short registration form and arrival note.\n\nMaya", "Hi Marcus,\n\nBefore-care begins at 8:00 a.m. I included the full camp day and pickup instructions below.\n\nMaya", "Hi Priya,\n\nBoth Saturday groups have space, and the sibling rate is reflected in the enrollment summary.\n\nMaya"],
  campaignNames: ["Returning-family spring priority", "Winter Break Lab enrollment", "School partnership follow-up"],
  contentTitles: ["What a first robotics trial feels like", "A parent’s guide to Makers Camp", "Inside our school enrichment partnerships", "Choosing the right Saturday studio"],
  resourceTitles: ["2026 program calendar", "Camp care and pickup guide", "School partnership overview", "Trial-class preparation checklist"],
  roadmapTitles: ["Family enrollment handoff", "Attendance exception queue", "School roster import", "Returning-family renewal signal", "Camp capacity forecast", "Instructor substitution workflow"],
};

export const NORTHLINE_PROFILE: DemoScenarioContentProfile = {
  supportingPeople: [
    { name: "Bethany Cross", company: "Cross Residence", role: "Homeowner" }, { name: "Caleb Dunn", company: "Dunn Residence", role: "Homeowner" },
    { name: "Rosa Delgado", company: "Delgado Residence", role: "Homeowner" }, { name: "Neil Foster", company: "Foster Residence", role: "Homeowner" },
    { name: "April Gaines", company: "Gaines Residence", role: "Homeowner" }, { name: "Victor Huang", company: "Huang Residence", role: "Homeowner" },
    { name: "Leah Ingram", company: "Ingram Residence", role: "Homeowner" }, { name: "Scott Jarvis", company: "Jarvis Residence", role: "Homeowner" },
    { name: "Marisol Klein", company: "Klein Duplex", role: "Property owner" }, { name: "Derek Long", company: "Long Residence", role: "Homeowner" },
    { name: "Paula McBride", company: "McBride Residence", role: "Homeowner" }, { name: "Gavin Nwosu", company: "Nwosu Residence", role: "Homeowner" },
    { name: "Irene Olson", company: "Olson Residence", role: "Homeowner" }, { name: "Damon Pierce", company: "Pierce Residence", role: "Homeowner" },
    { name: "Nadia Quinn", company: "Quinn Residence", role: "Homeowner" }, { name: "Trevor Russo", company: "Russo Residence", role: "Homeowner" },
    { name: "Alicia Stone", company: "Stone Residence", role: "Homeowner" }, { name: "Kevin Tran", company: "Tran Residence", role: "Homeowner" },
    { name: "Brooke Underwood", company: "Underwood Residence", role: "Homeowner" }, { name: "Wes Vega", company: "Vega Residence", role: "Homeowner" },
    { name: "Yara Wilson", company: "Wilson Residence", role: "Homeowner" }, { name: "Zach Yates", company: "Yates Residence", role: "Homeowner" },
    { name: "Helen Archer", company: "Cedar Court Condominiums", role: "Property manager" }, { name: "Mike Bishop", company: "Bishop Commercial", role: "Facilities director" },
    { name: "Tamara Clay", company: "Willow Ridge HOA", role: "Board president" }, { name: "Frank Dominguez", company: "Dominguez Insurance", role: "Claims adjuster" },
    { name: "Sharon Estes", company: "Estes Realty Group", role: "Broker" }, { name: "Cole Freeman", company: "Freeman Restoration", role: "Referral partner" },
  ],
  opportunities: [
    { name: "Walsh storm restoration", value: 18400, source: "Storm landing page", nextAction: "Confirm Thursday inspection window" }, { name: "Coleman roof replacement", value: 23600, source: "Neighbor referral", nextAction: "Explain ventilation options in estimate" },
    { name: "Moore rental inspection", value: 1450, source: "Property manager", nextAction: "Coordinate tenant access" }, { name: "Ellis hail claim", value: 19750, source: "Insurance referral", nextAction: "Upload the photo report for adjuster" },
    { name: "Lakeview HOA exterior review", value: 8600, source: "HOA board inquiry", nextAction: "Schedule the board walkthrough" }, { name: "Park gutter and fascia", value: 7200, source: "Past customer", nextAction: "Confirm copper color selection" },
    { name: "Cross emergency tarp", value: 1250, source: "After-hours call", nextAction: "Dispatch tarp crew before rain" }, { name: "Dunn architectural shingles", value: 21400, source: "Google Business", nextAction: "Deliver shingle sample board" },
    { name: "Delgado skylight leak", value: 4800, source: "Website inquiry", nextAction: "Inspect flashing and interior moisture" }, { name: "Foster flat-roof repair", value: 9800, source: "Commercial referral", nextAction: "Review core sample results" },
    { name: "Gaines siding replacement", value: 16800, source: "Yard sign", nextAction: "Measure west elevation" }, { name: "Huang chimney flashing", value: 3650, source: "Repeat customer", nextAction: "Confirm masonry coordination" },
    { name: "Ingram insurance supplement", value: 5400, source: "Adjuster introduction", nextAction: "Submit code-upgrade documentation" }, { name: "Jarvis roof tune-up", value: 2100, source: "Maintenance reminder", nextAction: "Book spring maintenance visit" },
    { name: "Cedar Court membrane project", value: 68500, source: "Property portfolio", nextAction: "Present phased access plan" }, { name: "Willow Ridge inspection day", value: 12800, source: "Board referral", nextAction: "Confirm homeowner time blocks" },
    { name: "Bishop Commercial drainage", value: 14900, source: "Facilities network", nextAction: "Map scupper and downspout changes" }, { name: "Estes pre-listing roof report", value: 950, source: "Realtor partner", nextAction: "Deliver report before listing photos" },
  ],
  conversations: [
    { subject: "Inspection after last night’s storm", intent: "inspection_request", inbound: "We found shingles in the yard after the storm. Can someone inspect the roof this week?", outbound: "Yes. I reserved Thursday afternoon and included what our inspector will document.", followUp: "Thursday works. The gate code is in my reply." },
    { subject: "Ventilation line items", intent: "estimate_question", inbound: "We reviewed the estimate and have two questions about the ventilation line items.", outbound: "I separated those items and added a plain-language explanation of each option.", followUp: "The ridge-vent option makes sense. Please keep that one." },
    { subject: "Friday crew start", intent: "production_update", inbound: "Is Friday’s crew start still confirmed?", outbound: "Friday is confirmed. The material delivery is complete and the weather window remains clear.", followUp: "Thanks. We will keep the driveway clear." },
    { subject: "Insurance photo report", intent: "claims_documentation", inbound: "The adjuster needs the slope photos before reviewing our supplement.", outbound: "The labeled slope and collateral-damage photos are organized in the claim packet.", followUp: "I sent the packet link to the adjuster." },
    { subject: "Copper gutter color", intent: "selection", inbound: "Can we see aged copper next to the brick before ordering?", outbound: "I scheduled a sample drop and noted the south-wall brick for comparison.", followUp: "Please leave both samples by the side door." },
    { subject: "Emergency tarp arrival", intent: "urgent_service", inbound: "Water is coming through the guest-room ceiling and rain starts again tonight.", outbound: "The tarp crew is dispatched with an arrival window of 2–4 p.m.", followUp: "The attic access is open and someone will be home." },
    { subject: "Cedar Court access plan", intent: "project_logistics", inbound: "Residents cannot lose both stairwell entrances at the same time.", outbound: "The phased plan keeps one entrance open and gives each building a 48-hour notice.", followUp: "That addresses the board’s main concern." },
    { subject: "Code-upgrade supplement", intent: "insurance_follow_up", inbound: "Did the carrier receive the ice-and-water code documentation?", outbound: "The supplement and municipality excerpt were submitted under the existing claim number.", followUp: "I can see the new document in the carrier portal." },
    { subject: "Spring tune-up timing", intent: "maintenance_booking", inbound: "Can the tune-up happen before the cottonwood season starts?", outbound: "I reserved the April 9 morning window and added gutter clearing.", followUp: "April 9 is perfect." },
    { subject: "Pre-listing roof report", intent: "report_deadline", inbound: "Photography moved up. Can the roof report be ready by Wednesday?", outbound: "The inspection is Tuesday morning and the signed report will be delivered that afternoon.", followUp: "That keeps the listing on schedule." },
  ],
  tasks: ["Confirm the Walsh inspection window", "Send Coleman’s ventilation comparison", "Coordinate Moore tenant access", "Upload Ellis claim photos", "Schedule the Lakeview board walkthrough", "Confirm Park’s gutter color", "Dispatch the Cross tarp crew", "Deliver Dunn’s shingle samples", "Inspect Delgado skylight flashing", "Review Foster core sample results", "Measure the Gaines west elevation", "Confirm Huang masonry coordination", "Submit the Ingram code supplement", "Book the Jarvis spring tune-up", "Present Cedar Court’s access phases", "Confirm Willow Ridge time blocks", "Map Bishop Commercial drainage", "Deliver the Estes pre-listing report"],
  actionReasons: ["Storm damage and a requested inspection window are confirmed.", "The estimate question maps to two documented ventilation options.", "The production start depends on delivered materials and the current weather window.", "The adjuster requested a bounded photo packet tied to the claim.", "Active water intrusion requires the approved emergency-tarp workflow.", "The board’s access constraint is resolved in the revised phase plan."],
  replyBodies: ["Hi Lena,\n\nThursday afternoon is reserved for the storm inspection. We’ll document every slope, flashing detail, and visible collateral hit.\n\nEvan", "Hi Andre,\n\nI separated the ventilation options and highlighted the ridge-vent configuration included in the estimate.\n\nEvan", "Hi Bethany,\n\nThe emergency tarp crew is dispatched for 2–4 p.m. today. Nothing else is required before they arrive.\n\nEvan"],
  campaignNames: ["Storm inspection availability", "Spring roof tune-up", "Realtor report partner update"],
  contentTitles: ["What a storm inspection documents", "Reading a roofing estimate without guesswork", "How production-day access works", "When a roof repair becomes a replacement"],
  resourceTitles: ["Storm damage photo checklist", "Roofing estimate guide", "Production-day preparation sheet", "Warranty and maintenance overview"],
  roadmapTitles: ["Weather hold automation", "Inspection photo packet", "Material delivery exception", "Insurance supplement tracker", "Crew capacity board", "Warranty registration receipt"],
};

export const HARBORLINE_PROFILE: DemoScenarioContentProfile = {
  supportingPeople: [
    { name: "Amelia Boyd", company: "Crescent Foods", role: "VP Marketing" }, { name: "Nathan Cho", company: "Crescent Foods", role: "Finance director" },
    { name: "Bianca Flores", company: "Lumen Health", role: "Chief operating officer" }, { name: "Connor Hale", company: "Lumen Health", role: "Growth lead" },
    { name: "Mei Ito", company: "Fieldstone Capital", role: "Managing director" }, { name: "Dylan James", company: "Fieldstone Capital", role: "Principal" },
    { name: "Kira Lowell", company: "Juniper Works", role: "Founder" }, { name: "Elias Moss", company: "Juniper Works", role: "Head of sales" },
    { name: "Anika Nair", company: "Aperture Learning", role: "Chief executive officer" }, { name: "Peter Owens", company: "Aperture Learning", role: "Marketing director" },
    { name: "Celeste Price", company: "Meridian Bio", role: "Commercial director" }, { name: "Rohan Sethi", company: "Meridian Bio", role: "Product marketing lead" },
    { name: "Tessa Vaughn", company: "Vaughn Advisory", role: "Managing partner" }, { name: "Ian Webb", company: "Vaughn Advisory", role: "Operations manager" },
    { name: "Mina Xu", company: "Northstar Robotics", role: "Chief of staff" }, { name: "Aaron Young", company: "Northstar Robotics", role: "Revenue lead" },
    { name: "Zoe Alvarez", company: "Commonwell", role: "Founder" }, { name: "Blake Conrad", company: "Commonwell", role: "Head of partnerships" },
    { name: "Nora Dyer", company: "Redwood Legal", role: "Practice director" }, { name: "Sanjay Iyer", company: "Redwood Legal", role: "Managing partner" },
    { name: "Elise Jordan", company: "Fable Commerce", role: "VP Ecommerce" }, { name: "Martin Ko", company: "Fable Commerce", role: "Analytics lead" },
    { name: "Ava Larson", company: "Beacon Climate", role: "Co-founder" }, { name: "George Malik", company: "Beacon Climate", role: "Commercial lead" },
    { name: "Renee Novak", company: "Novak Ventures", role: "Operating partner" }, { name: "Sam Osei", company: "Osei Product Studio", role: "Founder" },
    { name: "Clara Penn", company: "Penn Executive Search", role: "President" }, { name: "Henry Ruiz", company: "Atlas Manufacturing", role: "Strategy director" },
  ],
  opportunities: [
    { name: "Northwind conversion rebuild", value: 48000, source: "Website assessment", nextAction: "Review the two highest-impact conversion gaps" }, { name: "Whitfield growth operations retainer", value: 72000, source: "Partner referral", nextAction: "Separate reporting from the operating scope" },
    { name: "Brightwater demand program", value: 58500, source: "Founder introduction", nextAction: "Confirm discovery stakeholders" }, { name: "Atwell referral campaign", value: 26000, source: "Existing client", nextAction: "Approve the exclusion list" },
    { name: "Halcyon client reporting system", value: 36000, source: "Quarterly review", nextAction: "Map partner reporting decisions" }, { name: "Crescent category launch", value: 64000, source: "Executive referral", nextAction: "Align finance and marketing success measures" },
    { name: "Lumen lifecycle redesign", value: 52000, source: "Website inquiry", nextAction: "Audit handoff between sales and onboarding" }, { name: "Fieldstone portfolio narrative", value: 44000, source: "Conference conversation", nextAction: "Select three portfolio proof points" },
    { name: "Juniper sales operating system", value: 81000, source: "Founder network", nextAction: "Review pipeline governance gaps" }, { name: "Aperture enrollment campaign", value: 39500, source: "Content referral", nextAction: "Confirm audience and offer constraints" },
    { name: "Meridian launch research", value: 33000, source: "Product leader referral", nextAction: "Approve interview cohort" }, { name: "Vaughn advisory repositioning", value: 42000, source: "Past collaborator", nextAction: "Choose decision-maker interview dates" },
    { name: "Northstar revenue narrative", value: 55000, source: "Board introduction", nextAction: "Reconcile product and sales language" }, { name: "Commonwell partnership engine", value: 47000, source: "Partner inquiry", nextAction: "Score the first partner cohort" },
    { name: "Redwood practice growth plan", value: 68000, source: "Managing partner referral", nextAction: "Review conflict-safe outreach" }, { name: "Fable retention analytics", value: 61000, source: "Analytics assessment", nextAction: "Validate the churn cohort definition" },
    { name: "Beacon commercial launch", value: 75000, source: "Investor introduction", nextAction: "Confirm launch decision rights" }, { name: "Atlas channel strategy", value: 57000, source: "Executive search partner", nextAction: "Schedule distributor interviews" },
  ],
  conversations: [
    { subject: "Website assessment priorities", intent: "discovery_request", inbound: "The assessment was helpful. Can we talk through the two highest-priority conversion issues?", outbound: "Absolutely. I linked each recommendation to the evidence and proposed a focused 30-minute review.", followUp: "Tuesday morning works for our operations and marketing leads." },
    { subject: "Revised scope structure", intent: "proposal_revision", inbound: "Please separate reporting from the main scope so finance can review it independently.", outbound: "Done. Reporting is now its own line with timing, ownership, and acceptance criteria.", followUp: "Finance has the revised version for Friday review." },
    { subject: "Campaign exclusion list", intent: "campaign_approval", inbound: "The campaign draft looks right. Can you confirm the exclusion list before launch?", outbound: "Confirmed. Existing clients, prior replies, and suppressed contacts are excluded in the dry run.", followUp: "Approved from our side once the dry-run count is attached." },
    { subject: "Discovery stakeholder map", intent: "stakeholder_alignment", inbound: "Should finance join the first Brightwater discovery session?", outbound: "Finance is most useful in session two, after we map the current demand and handoff model.", followUp: "That sequencing works. I will invite operations first." },
    { subject: "Partner reporting decisions", intent: "reporting_design", inbound: "The partners want fewer charts and clearer decisions in the monthly report.", outbound: "I reduced the report to pipeline movement, client risk, delivery capacity, and three decisions.", followUp: "This is much closer to how the meeting actually runs." },
    { subject: "Category launch measures", intent: "success_metrics", inbound: "Marketing and finance are using different definitions of launch success.", outbound: "I drafted one shared scorecard separating leading demand, conversion, and recognized revenue.", followUp: "Please use that structure in Thursday’s alignment session." },
    { subject: "Sales-to-onboarding handoff", intent: "operations_audit", inbound: "Clients repeat the same information after contracts are signed.", outbound: "The audit found three fields that can move directly from opportunity to onboarding.", followUp: "Let’s prioritize the handoff before changing nurture." },
    { subject: "Portfolio proof points", intent: "narrative_review", inbound: "We need proof points that work for operators, not just investors.", outbound: "I selected three examples with measurable operating change and named source evidence.", followUp: "The second example will resonate most with our operating partners." },
    { subject: "Interview cohort approval", intent: "research_approval", inbound: "Does the research cohort include both current and lost opportunities?", outbound: "Yes—six current buyers, four lost evaluations, and two channel partners, with no overlap.", followUp: "Approved. Recruiting can start Monday." },
    { subject: "Distributor interview schedule", intent: "scheduling", inbound: "Two distributors can meet next week, but only before 9 a.m.", outbound: "I held Tuesday and Thursday at 8:30 and attached the interview frame.", followUp: "Keep both holds; I will confirm names tomorrow." },
  ],
  tasks: ["Schedule Northwind’s conversion review", "Send Whitfield’s separated reporting scope", "Confirm Brightwater discovery stakeholders", "Attach Atwell’s campaign dry-run count", "Map Halcyon partner decisions", "Align Crescent launch measures", "Audit Lumen’s onboarding handoff", "Select Fieldstone proof points", "Review Juniper pipeline governance", "Confirm Aperture audience constraints", "Approve Meridian interview cohort", "Book Vaughn decision-maker interviews", "Reconcile Northstar revenue language", "Score Commonwell’s partner cohort", "Review Redwood conflict-safe outreach", "Validate Fable churn cohorts", "Confirm Beacon launch decision rights", "Schedule Atlas distributor interviews"],
  actionReasons: ["The assessment evidence identifies two bounded conversion priorities.", "Finance requested a separable reporting decision with explicit acceptance criteria.", "The campaign is ready only after exclusions and dry-run counts reconcile.", "Discovery sequencing depends on a confirmed stakeholder map.", "Partners asked for a decision-oriented reporting structure.", "The research cohort is approved and ready for bounded recruiting."],
  replyBodies: ["Hi Sarah,\n\nI linked the two highest-impact conversion issues to their evidence and held Tuesday morning for a focused review.\n\nAvery", "Hi Dana,\n\nReporting is now a separate scope line with timing, ownership, and acceptance criteria for finance.\n\nAvery", "Hi Ray,\n\nThe dry run excludes existing clients, prior replies, and suppressed contacts. I attached the reconciled audience count.\n\nAvery"],
  campaignNames: ["Website assessment follow-up", "Decision-maker research invitation", "Referral partner reactivation"],
  contentTitles: ["The operating cost of unclear handoffs", "How to turn an assessment into a decision", "A practical revenue-operations scorecard", "What evidence belongs in a proposal"],
  resourceTitles: ["Website assessment brief", "Discovery stakeholder map", "Campaign approval checklist", "Monthly operating review template"],
  roadmapTitles: ["Assessment-to-opportunity handoff", "Proposal evidence pack", "Decision-maker context sheet", "Campaign exclusion audit", "Client reporting decision log", "Referral attribution model"],
};

const people = (rows: Array<[string, string, string]>) => rows.map(([name, company, role]) => ({ name, company, role }));

export const ALDER_RIDGE_PROFILE: DemoScenarioContentProfile = {
  supportingPeople: people([
    ["Janet Alvarez", "Alvarez Household", "Prospective client"], ["Malcolm Byrd", "Byrd Household", "Prospective client"],
    ["Renee Carter", "Carter Household", "Prospective client"], ["Darius Dixon", "Dixon Household", "Prospective client"],
    ["Elise Freeman", "Freeman Household", "Prospective client"], ["Owen Gallagher", "Gallagher Household", "Prospective client"],
    ["Nadia Hassan", "Hassan Household", "Prospective client"], ["Caleb Ingram", "Ingram Household", "Prospective client"],
    ["Tara Jimenez", "Jimenez Household", "Prospective client"], ["Miles Kim", "Kim Household", "Prospective client"],
    ["Sonya Lewis", "Lewis Household", "Prospective client"], ["Peter Morgan", "Morgan Household", "Prospective client"],
    ["Alina Novak", "Novak Household", "Prospective client"], ["Terrence Owens", "Owens Household", "Prospective client"],
    ["Maya Patel", "Patel Household", "Prospective client"], ["Quentin Reed", "Reed Household", "Prospective client"],
    ["Iris Santos", "Santos Household", "Prospective client"], ["Evan Turner", "Turner Household", "Prospective client"],
    ["Bianca Vega", "Vega Household", "Prospective client"], ["Andre Wallace", "Wallace Household", "Prospective client"],
    ["Celia Xu", "Xu Household", "Prospective client"], ["Marcus Young", "Young Household", "Prospective client"],
    ["Kendall Brooks", "Brooks Physical Therapy", "Care coordinator"], ["Leah Chapman", "Chapman Auto Body", "Records manager"],
    ["Hector Flores", "Metro Translation Partners", "Interpreter coordinator"], ["Wendy Grant", "Grant Medical Records", "Records custodian"],
    ["Anika Shah", "Clearview Imaging", "Referral coordinator"], ["Paul Webb", "Webb Litigation Support", "Vendor liaison"],
  ]),
  opportunities: [
    { name: "Rivera collision intake", value: 42000, source: "After-hours web intake", nextAction: "Complete conflict review before consultation" },
    { name: "Bennett pedestrian consultation", value: 68000, source: "Former-client referral", nextAction: "Confirm Tuesday attorney consultation" },
    { name: "Choi rideshare intake", value: 51000, source: "Organic search", nextAction: "Request the incident report authorization" },
    { name: "Dawson premises inquiry", value: 36000, source: "Website chat", nextAction: "Review the timeline for intake completeness" },
    { name: "Evans delivery-vehicle consultation", value: 74000, source: "Medical partner referral", nextAction: "Send the secure document checklist" },
    { name: "Foster bicycle incident", value: 29000, source: "Community referral", nextAction: "Confirm insurance-party names for conflicts" },
    { name: "Alvarez consultation follow-up", value: 46000, source: "Phone intake", nextAction: "Answer the retainer process question" },
    { name: "Byrd claim review", value: 57000, source: "Attorney referral", nextAction: "Schedule the case-fit review" },
    { name: "Carter roadway intake", value: 33000, source: "Local search", nextAction: "Collect the missing report number" },
    { name: "Dixon passenger consultation", value: 62000, source: "Website intake", nextAction: "Confirm consultation attendance" },
    { name: "Freeman property incident", value: 27000, source: "Past-client referral", nextAction: "Review the photo index" },
    { name: "Gallagher commercial collision", value: 88000, source: "Professional referral", nextAction: "Route the intake summary to senior review" },
    { name: "Hassan crosswalk inquiry", value: 39000, source: "Mobile landing page", nextAction: "Send the consultation preparation note" },
    { name: "Ingram insurance follow-up", value: 31000, source: "Intake callback", nextAction: "Log the carrier contact details" },
    { name: "Jimenez consultation decision", value: 54000, source: "Community event", nextAction: "Follow up after attorney review" },
    { name: "Kim vehicle-loss intake", value: 25000, source: "Referral partner", nextAction: "Confirm property-damage scope boundary" },
    { name: "Lewis incident consultation", value: 43000, source: "Website form", nextAction: "Collect signed records authorization" },
    { name: "Morgan claim handoff", value: 71000, source: "Co-counsel referral", nextAction: "Confirm handoff documents received" },
  ],
  conversations: [
    { subject: "Consultation after online intake", intent: "consultation_booking", inbound: "I completed the intake last night. Is there anything else needed before speaking with an attorney?", outbound: "Your intake is received. We need to complete a conflict review before confirming the consultation, and no legal assessment has been made yet.", followUp: "Understood. I sent the names requested for the conflict review." },
    { subject: "Tuesday attorney consultation", intent: "appointment_confirmation", inbound: "Tuesday afternoon works. Can my spouse join the call?", outbound: "Yes. I reserved Tuesday at 2:30 and added your spouse as an attendee after the conflict review cleared.", followUp: "Thank you. We both received the calendar note." },
    { subject: "Incident report authorization", intent: "document_request", inbound: "I do not have the report yet. Can the firm request it?", outbound: "We can request it after receiving the signed authorization. I sent the secure authorization link without making any representation about the matter.", followUp: "The authorization is signed and submitted." },
    { subject: "Retainer process question", intent: "engagement_question", inbound: "If the attorney accepts the matter, how does the agreement work?", outbound: "The attorney will explain the engagement terms during the consultation. I attached the plain-language process overview for review beforehand.", followUp: "That answers my process question. I will review it before the call." },
    { subject: "Secure document checklist", intent: "onboarding_documents", inbound: "Which documents should I upload before Friday?", outbound: "The secure checklist requests the incident report, insurer correspondence, and care-provider list. Please do not email sensitive records directly.", followUp: "I used the secure link and uploaded the available documents." },
    { subject: "Missing report number", intent: "intake_completion", inbound: "I found the report number after submitting the form. Where should I add it?", outbound: "Reply with only the report number and we will attach it to the intake record. Do not include medical details in email.", followUp: "The report number is CP-20418." },
    { subject: "Consultation reminder", intent: "appointment_reminder", inbound: "Is tomorrow's consultation by phone or video?", outbound: "It is a video consultation. The secure link and preparation note are in the calendar invitation.", followUp: "I found the link. Thank you." },
    { subject: "Interpreter for consultation", intent: "accessibility_request", inbound: "Can the firm provide a Spanish interpreter for the consultation?", outbound: "Yes. I placed an interpreter request and will confirm once scheduling responds.", followUp: "That would be very helpful." },
    { subject: "Attorney review status", intent: "review_status", inbound: "Has the attorney had a chance to review the intake summary?", outbound: "The summary is in attorney review. We will contact you after that review without predicting the outcome.", followUp: "Thank you for the clear update." },
    { subject: "Referral handoff documents", intent: "referral_handoff", inbound: "Did the files from referring counsel arrive?", outbound: "The handoff index arrived and is being reconciled against the secure file list.", followUp: "I will ask counsel to resend the missing correspondence." },
  ],
  tasks: ["Complete Rivera conflict review", "Confirm Bennett consultation attendees", "Send Choi authorization link", "Review Dawson intake timeline", "Reconcile Evans secure uploads", "Confirm Foster conflict-check names", "Answer Alvarez engagement-process question", "Schedule Byrd case-fit review", "Attach Carter report number", "Send Dixon consultation reminder", "Index Freeman incident photos", "Route Gallagher summary to senior review", "Arrange Hassan interpreter request", "Log Ingram carrier contacts", "Follow up with Jimenez after review", "Confirm Kim scope boundary", "Collect Lewis records authorization", "Reconcile Morgan handoff index"],
  actionReasons: ["The intake is complete enough for a conflict review, but not for legal advice.", "The requested consultation time is available after conflict clearance.", "A signed authorization is required before requesting the report.", "The secure upload set can be checked without exposing document contents.", "The interpreter request must be confirmed before the consultation.", "The referral handoff is missing one indexed document."],
  replyBodies: ["Hi Sofia,\n\nWe received your intake and are completing the conflict review. We will confirm the consultation once that check is clear. No legal assessment has been made yet.\n\nJordan", "Hi Malcolm,\n\nTuesday at 2:30 p.m. is reserved. Your calendar note includes the secure video link and preparation checklist.\n\nJordan", "Hi Renee,\n\nI sent the secure authorization form required before the incident report can be requested.\n\nJordan"],
  campaignNames: ["Unscheduled consultation follow-up", "Post-consultation document reminder", "Former-client referral thank-you"],
  contentTitles: ["What happens after a legal intake", "Preparing for an attorney consultation", "How secure document collection works", "Understanding the conflict-review step"],
  resourceTitles: ["Consultation preparation guide", "Secure document checklist", "Intake process overview", "Records authorization instructions"],
  roadmapTitles: ["Conflict-review receipt", "Secure intake completeness signal", "Consultation reminder sequence", "Referral handoff checklist", "Interpreter scheduling alert", "Document authorization tracker"],
};

export const LEDGERSTONE_PROFILE: DemoScenarioContentProfile = {
  supportingPeople: people([
    ["Elena Abbott", "Abbott Architecture", "Founder"], ["Jonah Blake", "Blake Dental Group", "Practice owner"], ["Mina Castillo", "Castillo Design Co", "Managing director"], ["Theo Donovan", "Donovan Fabrication", "President"],
    ["Rhea Ellis", "Ellis Therapy Collective", "Clinical director"], ["Andre Fox", "Fox Hospitality", "Operator"], ["Carmen Gupta", "Gupta Consulting", "Principal"], ["Liam Hayes", "Hayes Property Services", "Owner"],
    ["Sora Ito", "Ito Product Studio", "Founder"], ["Nolan James", "James Veterinary Care", "Practice manager"], ["Priya Kapoor", "Kapoor Engineering", "Partner"], ["Derek Lin", "Lin Retail Group", "Controller"],
    ["Mara Ortiz", "Ortiz Creative", "President"], ["Calvin Price", "Price Logistics", "Operations director"], ["Nia Quade", "Quade Recruiting", "Founder"], ["Owen Russell", "Russell Food Works", "Owner"],
    ["Tessa Singh", "Singh Wellness", "Managing member"], ["Marcus Tate", "Tate Construction", "President"], ["Ivy Underwood", "Underwood Events", "Founder"], ["Evan Vega", "Vega Software", "Chief executive officer"],
    ["Willa Chen", "Chen Legal Operations", "Director"], ["Hector Yarrow", "Yarrow Auto Group", "Controller"], ["Dana Brooks", "First Harbor Bank", "Business banker"], ["Felix Cooper", "Cooper Benefits", "Benefits advisor"],
    ["Grace Moore", "Moore Payroll Services", "Implementation manager"], ["Samir Patel", "Patel Wealth Partners", "Advisor"], ["Rosa Reed", "Reed Bookkeeping", "Referral partner"], ["Cole Turner", "Turner Systems", "Technology consultant"],
  ]),
  opportunities: [
    { name: "Monroe monthly close advisory", value: 24000, source: "Banker referral", nextAction: "Review the close-calendar gaps" }, { name: "Park tax planning engagement", value: 18500, source: "Client referral", nextAction: "Confirm entity and owner documents" },
    { name: "Summit fractional controller scope", value: 42000, source: "Website assessment", nextAction: "Send the revised reporting scope" }, { name: "Riverside cash-flow forecast", value: 15000, source: "Workshop attendee", nextAction: "Schedule forecast assumptions review" },
    { name: "Abbott project margin review", value: 21600, source: "Professional referral", nextAction: "Map project-cost source files" }, { name: "Blake practice KPI reporting", value: 28800, source: "Peer introduction", nextAction: "Confirm monthly reporting owners" },
    { name: "Castillo year-end readiness", value: 12400, source: "Content download", nextAction: "Collect prior-year workpapers" }, { name: "Donovan inventory reconciliation", value: 33000, source: "Bank partner", nextAction: "Review inventory cut-off process" },
    { name: "Ellis contractor conversion", value: 9800, source: "Payroll partner", nextAction: "Confirm worker classification inputs" }, { name: "Fox location reporting", value: 36000, source: "Owner network", nextAction: "Separate location-level chart of accounts" },
    { name: "Gupta quarterly planning", value: 14400, source: "Past engagement", nextAction: "Approve the quarterly cadence" }, { name: "Hayes receivables cleanup", value: 11200, source: "Website inquiry", nextAction: "Import the aged receivables report" },
    { name: "Ito studio profitability model", value: 19800, source: "Founder referral", nextAction: "Validate service-line definitions" }, { name: "James payroll controls", value: 16800, source: "Benefits advisor", nextAction: "Schedule payroll walkthrough" },
    { name: "Kapoor backlog reporting", value: 27000, source: "Professional network", nextAction: "Reconcile signed work and billing plans" }, { name: "Lin board reporting pack", value: 22500, source: "Controller referral", nextAction: "Choose the decision metrics" },
    { name: "Ortiz bookkeeping transition", value: 13200, source: "Software partner", nextAction: "Confirm migration cutover date" }, { name: "Price lender covenant reporting", value: 31200, source: "Bank introduction", nextAction: "Review covenant definitions with finance" },
  ],
  conversations: [
    { subject: "Monthly close calendar", intent: "process_review", inbound: "Our close drifts past the fifteenth because approvals happen in email. Can you review the calendar?", outbound: "Yes. I mapped each close dependency, owner, and approval point for a focused review Thursday.", followUp: "Thursday works. Our operations lead will join." },
    { subject: "Entity document checklist", intent: "document_collection", inbound: "Which entity documents are still missing for tax planning?", outbound: "The checklist shows the operating agreement and current ownership schedule as outstanding. Please use the secure upload link.", followUp: "Both files are uploaded now." },
    { subject: "Revised controller scope", intent: "proposal_revision", inbound: "Can reporting be separated from the weekly controller work?", outbound: "I separated reporting into its own line with monthly timing, ownership, and acceptance criteria.", followUp: "That will make the partner review easier." },
    { subject: "Forecast assumptions review", intent: "meeting_booking", inbound: "Should sales and operations both attend the forecast review?", outbound: "Yes. Sales owns the revenue assumptions and operations owns capacity, so both are needed for the first session.", followUp: "I invited both leads for Wednesday." },
    { subject: "Project-cost source files", intent: "integration_mapping", inbound: "Our labor hours and vendor costs live in different tools. What should we export?", outbound: "I sent a bounded source checklist for time, vendor bills, project codes, and invoice status.", followUp: "The four exports are in the secure folder." },
    { subject: "Monthly reporting owners", intent: "ownership_alignment", inbound: "Who should certify the practice KPI report each month?", outbound: "The office manager certifies volume and payroll; the owner signs off on production and adjustments.", followUp: "That split matches how we work." },
    { subject: "Prior-year workpapers", intent: "year_end_readiness", inbound: "Do you need the entire prior-year folder?", outbound: "Only the signed return, depreciation schedule, trial balance, and open notice list are required for readiness review.", followUp: "Those four items are uploaded." },
    { subject: "Inventory cut-off walkthrough", intent: "controls_review", inbound: "Can the walkthrough happen before the month-end count?", outbound: "Yes. Tuesday gives us time to document receiving and shipping cut-off before the count starts.", followUp: "Tuesday morning is confirmed." },
    { subject: "Quarterly planning cadence", intent: "renewal", inbound: "We want to continue, but four long meetings is too much.", outbound: "I revised the cadence to one decision meeting per quarter with asynchronous preparation.", followUp: "That cadence is approved." },
    { subject: "Covenant definition review", intent: "reporting_definition", inbound: "The bank and our books calculate adjusted EBITDA differently.", outbound: "I created a definition reconciliation for finance and the lender to review before the next certificate.", followUp: "Please send it to our banker for Friday." },
  ],
  tasks: ["Map Monroe close approvals", "Confirm Park entity documents", "Send Summit revised scope", "Book Riverside assumptions review", "Validate Abbott source exports", "Assign Blake report certifications", "Review Castillo workpapers", "Schedule Donovan cut-off walkthrough", "Confirm Ellis classification inputs", "Separate Fox location accounts", "Approve Gupta quarterly cadence", "Import Hayes aging report", "Validate Ito service lines", "Book James payroll walkthrough", "Reconcile Kapoor backlog", "Choose Lin board metrics", "Confirm Ortiz cutover date", "Review Price covenant definitions"],
  actionReasons: ["The close review has named owners and a confirmed meeting.", "The secure checklist shows exactly two outstanding entity documents.", "The client requested a separately reviewable reporting scope.", "Forecast assumptions need both sales and capacity owners present.", "The quarterly cadence revision is explicitly approved.", "Finance and the lender need one reconciled covenant definition."],
  replyBodies: ["Hi Claire,\n\nI mapped the close dependencies and approval owners for Thursday's review.\n\nMorgan", "Hi Daniel,\n\nThe secure checklist now shows the operating agreement and ownership schedule as received.\n\nMorgan", "Hi Amina,\n\nReporting is separated into a monthly scope line with clear ownership and acceptance criteria.\n\nMorgan"],
  campaignNames: ["Year-end readiness review", "Quarterly planning renewal", "Banker referral follow-up"],
  contentTitles: ["A close calendar people can actually follow", "What belongs in a monthly management report", "Preparing for a cash-flow forecast", "Moving client documents out of email"],
  resourceTitles: ["Monthly close checklist", "Secure document request list", "Forecast assumptions worksheet", "Quarterly decision-meeting template"],
  roadmapTitles: ["Close dependency tracker", "Client document completeness", "Reporting certification receipt", "Forecast assumption versioning", "Recurring deadline brief", "Advisory renewal signal"],
};

export const HEARTHLINE_PROFILE: DemoScenarioContentProfile = {
  supportingPeople: people([
    ["Mara Benson", "Benson Household", "Buyer"], ["Theo Chang", "Chang Household", "Seller"], ["Priya Desai", "Desai Household", "Buyer"], ["Nolan Edwards", "Edwards Household", "Seller"],
    ["Renee Foster", "Foster Household", "Buyer"], ["Caleb Grant", "Grant Household", "Investor"], ["Iris Hill", "Hill Household", "Seller"], ["Marcus Ibarra", "Ibarra Household", "Buyer"],
    ["Sora Jensen", "Jensen Household", "Buyer"], ["Owen King", "King Household", "Seller"], ["Leila Morris", "Morris Household", "Buyer"], ["Damon Nguyen", "Nguyen Household", "Investor"],
    ["Talia Ortiz", "Ortiz Household", "Seller"], ["Evan Park", "Park Household", "Buyer"], ["Nia Quinn", "Quinn Household", "Buyer"], ["Andre Rivera", "Rivera Household", "Seller"],
    ["Celeste Stone", "Stone Household", "Buyer"], ["Miles Turner", "Turner Household", "Seller"], ["Alina Vega", "Vega Household", "Buyer"], ["Jonah Wilson", "Wilson Household", "Investor"],
    ["Grace Xu", "Xu Household", "Seller"], ["Hector Young", "Young Household", "Buyer"], ["Dana Cole", "Cole Mortgage", "Loan officer"], ["Felix Lane", "Lane Home Inspection", "Inspector"],
    ["Monica Ray", "Ray Closing Services", "Closing coordinator"], ["Sam Wu", "Wu Property Photography", "Photographer"], ["Rosa Bell", "Bell Title Group", "Title officer"], ["Kira Shah", "Shah Relocation", "Relocation partner"],
  ]),
  opportunities: [
    { name: "Carver first-home search", value: 14200, source: "Portal inquiry", nextAction: "Confirm Saturday showing route" }, { name: "Langston listing consultation", value: 18600, source: "Past-client referral", nextAction: "Deliver the pricing review" },
    { name: "Mehta relocation search", value: 21800, source: "Relocation partner", nextAction: "Approve the neighborhood shortlist" }, { name: "Olsen downsizing plan", value: 16400, source: "Community seminar", nextAction: "Schedule the home-preparation walk" },
    { name: "Benson condo search", value: 9800, source: "Instagram inquiry", nextAction: "Clarify association requirements" }, { name: "Chang spring listing", value: 17200, source: "Home valuation page", nextAction: "Book photography and staging review" },
    { name: "Desai school-district search", value: 20100, source: "Portal registration", nextAction: "Send the commute comparison" }, { name: "Edwards estate sale", value: 15400, source: "Attorney referral", nextAction: "Confirm decision-maker availability" },
    { name: "Foster townhome tour", value: 11600, source: "Open house", nextAction: "Arrange lender preapproval call" }, { name: "Grant duplex acquisition", value: 24600, source: "Investor network", nextAction: "Review rent-roll assumptions" },
    { name: "Hill pre-market listing", value: 19300, source: "Neighborhood referral", nextAction: "Approve launch timeline" }, { name: "Ibarra move-up search", value: 22800, source: "Past client", nextAction: "Coordinate sale and purchase dates" },
    { name: "Jensen first showing", value: 10500, source: "Website chat", nextAction: "Confirm property priorities" }, { name: "King listing refresh", value: 14700, source: "Expired listing inquiry", nextAction: "Present revised positioning" },
    { name: "Morris new-construction search", value: 17900, source: "Builder event", nextAction: "Explain representation before site visit" }, { name: "Nguyen four-unit search", value: 31500, source: "Lender referral", nextAction: "Send underwriting-ready shortlist" },
    { name: "Ortiz closing coordination", value: 13200, source: "Sphere referral", nextAction: "Resolve title-document gap" }, { name: "Park annual home review", value: 8900, source: "Past-client nurture", nextAction: "Schedule equity review" },
  ],
  conversations: [
    { subject: "Saturday showing route", intent: "showing_schedule", inbound: "Can we see the three homes Saturday without crossing town twice?", outbound: "Yes. I reordered the route by neighborhood and held 10:00, 11:15, and 12:30 showing windows.", followUp: "That route works for us." },
    { subject: "Listing pricing review", intent: "listing_consultation", inbound: "We are ready to discuss price, but want to understand the nearby sales first.", outbound: "I prepared a pricing review separating recent closed sales, current competition, and condition adjustments.", followUp: "Please bring that to Thursday's consultation." },
    { subject: "Neighborhood shortlist", intent: "relocation", inbound: "Which areas fit a thirty-minute commute and a walkable center?", outbound: "I narrowed the search to three areas and noted commute assumptions, transit, and current inventory.", followUp: "The first and third areas look strongest." },
    { subject: "Home preparation walk", intent: "seller_preparation", inbound: "Should we make repairs before deciding to list?", outbound: "The preparation walk will separate safety, presentation, and optional improvements before any vendors are engaged.", followUp: "Tuesday afternoon is available." },
    { subject: "Association requirements", intent: "buyer_qualification", inbound: "We need a condo that permits one dog and has no rental requirement.", outbound: "I added both requirements to the search and flagged listings whose association documents still need confirmation.", followUp: "Thank you for not assuming the listing data is complete." },
    { subject: "Photography and staging", intent: "listing_launch", inbound: "Can photos happen next week if painting finishes Monday?", outbound: "I held Wednesday photography and a Tuesday staging review, contingent on the painting completion.", followUp: "The painter confirmed Monday." },
    { subject: "Commute comparison", intent: "property_research", inbound: "Can you compare train and driving time for the two finalists?", outbound: "I sent both commute ranges with the time-of-day assumptions used.", followUp: "The train option changes our ranking." },
    { subject: "Lender preapproval call", intent: "financing_handoff", inbound: "We want to tour again, but should speak with a lender first.", outbound: "I introduced the loan officer and held a Tuesday call without sharing financial details in this thread.", followUp: "Tuesday is confirmed with the lender." },
    { subject: "Sale and purchase timing", intent: "transaction_planning", inbound: "How do we avoid moving twice if our current home sells first?", outbound: "I mapped the listing, offer, contingency, and occupancy decisions for our planning call.", followUp: "Let's review the options Friday." },
    { subject: "Title document gap", intent: "closing_exception", inbound: "The closing checklist says one document is still missing. Which one?", outbound: "The title team is waiting for the recorded release. I assigned the follow-up and kept the closing date unchanged for now.", followUp: "Please let us know when the release is recorded." },
  ],
  tasks: ["Build Carver Saturday route", "Deliver Langston pricing review", "Approve Mehta neighborhood shortlist", "Book Olsen preparation walk", "Verify Benson association rules", "Confirm Chang photography hold", "Send Desai commute comparison", "Confirm Edwards decision makers", "Introduce Foster to lender", "Review Grant rent roll", "Approve Hill launch timeline", "Map Ibarra transaction dates", "Confirm Jensen property priorities", "Present King listing position", "Send Morris representation guide", "Build Nguyen underwriting shortlist", "Resolve Ortiz title document", "Schedule Park equity review"],
  actionReasons: ["Three showing windows are held and can be arranged into one efficient route.", "The pricing review uses current closed and active evidence.", "The relocation criteria narrow the search to three documented areas.", "The listing launch depends on a confirmed painting completion.", "The lender introduction can occur without sharing financial details.", "The title exception has one named missing document and owner."],
  replyBodies: ["Hi Maya,\n\nI reordered Saturday's route by neighborhood and held the three showing windows.\n\nAvery", "Hi Jordan,\n\nThe pricing review separates closed sales, current competition, and condition adjustments for Thursday.\n\nAvery", "Hi Noor,\n\nI narrowed the relocation search to three areas using the commute and walkability criteria we discussed.\n\nAvery"],
  campaignNames: ["Past-client annual home review", "Open-house follow-up", "Neighborhood seller update"],
  contentTitles: ["How a buyer showing route is planned", "Reading a listing pricing review", "Questions to ask before choosing a condo", "Coordinating a sale and purchase"],
  resourceTitles: ["Buyer consultation guide", "Listing preparation checklist", "Showing feedback report", "Closing milestone overview"],
  roadmapTitles: ["Portal-lead response receipt", "Showing route builder", "Listing launch dependency", "Long-term buyer nurture", "Closing exception alert", "Past-client equity review"],
};

export const COMMON_TABLE_PROFILE: DemoScenarioContentProfile = {
  supportingPeople: people([
    ["Elena Bryant", "Bryant Household", "Donor"], ["Marcus Chen", "Chen Household", "Monthly donor"], ["Nadia Davis", "Davis Household", "Volunteer"], ["Theo Ellis", "Ellis Family Fund", "Donor"],
    ["Rina Flores", "Flores Household", "Donor"], ["Caleb Grove", "Grove Household", "Volunteer"], ["Maya Hassan", "Hassan Household", "Program supporter"], ["Owen Ito", "Ito Household", "Donor"],
    ["Priya Jones", "Jones Household", "Volunteer captain"], ["Darius Kim", "Kim Household", "Donor"], ["Leah Morris", "Morris Household", "Monthly donor"], ["Andre Novak", "Novak Household", "Donor"],
    ["Celia Ortiz", "Ortiz Household", "Program supporter"], ["Miles Patel", "Patel Household", "Donor"], ["Tessa Reed", "Reed Household", "Volunteer"], ["Jonah Singh", "Singh Household", "Donor"],
    ["Iris Turner", "Turner Household", "Monthly donor"], ["Evan Wallace", "Wallace Household", "Donor"], ["Alina Xu", "Xu Household", "Volunteer"], ["Hector Yates", "Yates Household", "Donor"],
    ["Grace Bell", "Bell Household", "Program supporter"], ["Sam Rivera", "Rivera Household", "Donor"], ["Dana Coyle", "Northside Market", "Food partner"], ["Felix Green", "Greenway Logistics", "Transport partner"],
    ["Monica Hall", "Hall Family Foundation", "Program officer"], ["Kira Lane", "Lane Community School", "School liaison"], ["Rosa Moore", "Moore Health Center", "Referral partner"], ["Paul Shah", "Shah Civic Group", "Event partner"],
  ]),
  opportunities: [
    { name: "Hughes second-gift invitation", value: 250, source: "Spring appeal", nextAction: "Send the program-impact follow-up" }, { name: "Watson monthly giving conversation", value: 1200, source: "First-time donor", nextAction: "Offer the monthly pantry option" },
    { name: "Pine Family Fund renewal", value: 15000, source: "Foundation portfolio", nextAction: "Submit the outcome brief" }, { name: "Cedar Foods partnership", value: 8500, source: "Corporate inquiry", nextAction: "Confirm volunteer and food-safety scope" },
    { name: "Bryant donor stewardship", value: 500, source: "Community event", nextAction: "Share the neighborhood distribution update" }, { name: "Chen recurring upgrade", value: 600, source: "Monthly donor review", nextAction: "Send the anniversary thank-you" },
    { name: "Davis volunteer leadership", value: 1800, source: "Volunteer sign-up", nextAction: "Book captain orientation" }, { name: "Ellis Family Fund proposal", value: 25000, source: "Board introduction", nextAction: "Review the restricted-use language" },
    { name: "Flores second gift", value: 300, source: "Food drive", nextAction: "Send the first-gift impact note" }, { name: "Grove delivery route captain", value: 1600, source: "Volunteer referral", nextAction: "Confirm Saturday route training" },
    { name: "Hassan program referral", value: 2400, source: "Health partner", nextAction: "Route the eligibility question to staff" }, { name: "Ito year-end gift", value: 1000, source: "Newsletter", nextAction: "Schedule personal thank-you call" },
    { name: "Jones volunteer cohort", value: 3200, source: "School partner", nextAction: "Confirm group capacity" }, { name: "Kim workplace campaign", value: 12000, source: "Employer match", nextAction: "Approve campaign instructions" },
    { name: "Morris recurring renewal", value: 900, source: "Donor anniversary", nextAction: "Share twelve-month impact summary" }, { name: "Novak lapsed donor return", value: 450, source: "Lapsed supporter list", nextAction: "Send a no-pressure program update" },
    { name: "Hall Family Foundation report", value: 30000, source: "Active grant", nextAction: "Reconcile outcome and finance totals" }, { name: "Northside Market food partnership", value: 18000, source: "Partner referral", nextAction: "Finalize weekly pickup responsibilities" },
  ],
  conversations: [
    { subject: "Impact of my first gift", intent: "donor_stewardship", inbound: "I gave during the spring appeal and would love to know what happened next.", outbound: "Thank you. Your gift supported the neighborhood distribution program, and I linked the latest program update without assigning your gift to an unsupported claim.", followUp: "The update was helpful. Please keep me informed." },
    { subject: "Monthly pantry support", intent: "recurring_giving", inbound: "Can a monthly gift be directed to pantry staples?", outbound: "Yes. The monthly pantry option supports the published staples budget, and the designation appears before confirmation.", followUp: "Please send that option." },
    { subject: "Foundation outcome brief", intent: "grant_reporting", inbound: "Can the renewal brief separate households served from repeat visits?", outbound: "Yes. The draft now defines both measures and ties them to the same reporting period.", followUp: "That resolves our program officer's question." },
    { subject: "Corporate volunteer day", intent: "partner_planning", inbound: "We have twenty employees available. Can they volunteer together?", outbound: "The warehouse can host twelve per shift, so I proposed two shifts and included the food-safety orientation.", followUp: "Two shifts will work for our team." },
    { subject: "Donor anniversary thank-you", intent: "donor_retention", inbound: "I received the anniversary note and want to update my mailing address.", outbound: "Thank you for a full year of support. I sent the secure preference form so the address is updated once in the supporter record.", followUp: "The preference form is complete." },
    { subject: "Volunteer captain orientation", intent: "volunteer_onboarding", inbound: "What is covered in captain orientation?", outbound: "The session covers check-in, route safety, escalation, and the end-of-shift receipt. It does not include confidential program records.", followUp: "Thursday evening works for me." },
    { subject: "Restricted-use language", intent: "grant_proposal", inbound: "Please clarify whether the request includes transportation costs.", outbound: "I separated food purchasing, transportation, and volunteer coordination so the restricted-use decision is explicit.", followUp: "The separated budget is ready for review." },
    { subject: "Program eligibility question", intent: "program_inquiry", inbound: "Can you tell me whether a neighbor qualifies for delivery?", outbound: "A staff member will review eligibility directly. I routed the question without requesting personal details in email.", followUp: "Thank you for protecting their information." },
    { subject: "Workplace campaign instructions", intent: "campaign_approval", inbound: "Does the employee campaign explain the match deadline?", outbound: "Yes. The reviewed instructions include the employer match deadline and exclude anyone who opted out.", followUp: "Approved once the audience count is attached." },
    { subject: "Grant report totals", intent: "report_reconciliation", inbound: "The program and finance totals differ by one reporting week.", outbound: "I aligned both reports to the grant period and flagged the late-posted week separately rather than averaging it away.", followUp: "The reconciled view is ready for the board packet." },
  ],
  tasks: ["Send Hughes impact follow-up", "Offer Watson monthly pantry option", "Submit Pine outcome brief", "Confirm Cedar volunteer scope", "Share Bryant distribution update", "Send Chen anniversary thank-you", "Book Davis captain orientation", "Review Ellis restricted budget", "Send Flores first-gift note", "Confirm Grove route training", "Route Hassan eligibility question", "Schedule Ito thank-you call", "Confirm Jones group capacity", "Attach Kim campaign audience count", "Share Morris annual impact", "Send Novak program update", "Reconcile Hall grant totals", "Finalize Northside pickup roles"],
  actionReasons: ["The donor asked for a factual program update tied to the published appeal.", "A reviewed monthly giving designation is available.", "The foundation requested two explicitly defined outcome measures.", "The partner group exceeds one safe warehouse shift.", "The eligibility question requires staff review without personal data in email.", "Program and finance totals can reconcile to one grant period."],
  replyBodies: ["Hi Avery,\n\nThank you for your first gift. I linked the latest neighborhood distribution update and would be glad to keep you informed.\n\nElena", "Hi Marcus,\n\nThe monthly pantry option supports the published staples budget. Here is the reviewed designation page.\n\nElena", "Hi Nadia,\n\nCaptain orientation covers check-in, route safety, escalation, and the end-of-shift receipt. Thursday evening is available.\n\nElena"],
  campaignNames: ["First-to-second gift stewardship", "Volunteer captain orientation", "Lapsed supporter program update"],
  contentTitles: ["What happens after a first donation", "How neighborhood distribution days work", "Becoming a volunteer route captain", "Reading our program outcome report"],
  resourceTitles: ["Donor stewardship calendar", "Volunteer orientation guide", "Corporate service-day overview", "Grant outcome definitions"],
  roadmapTitles: ["First-gift acknowledgment receipt", "Second-gift journey", "Volunteer capacity signal", "Supporter identity review", "Grant-period reconciliation", "Partner pickup exception"],
};
