// Generated by scripts/build-extension-modules.mjs. Do not edit by hand.
// Source of truth: extensions/*.module.json. Run `npm run build:extensions`
// after changing a manifest; CI fails if this file drifts from the manifests.
import type { RevenueOSModule } from "./modules";

/** Nav link icon names are validated against an allowlist at build time and
 *  resolved to components in src/lib/admin/extension-nav-icons.ts. */
export interface ExtensionNavLink {
  moduleId: string;
  id: string;
  label: string;
  href: string;
  icon: string;
  description: string;
  keywords?: string;
  moreGroup?: "Revenue" | "Delivery" | "Intelligence" | "System" | "Sources";
}

export const EXTENSION_MODULES: readonly RevenueOSModule[] = [
  {
    id: "business-pulse",
    name: "Business pulse",
    description:
      "Bring pipeline risks, overdue commitments and upcoming meetings into one factual briefing.",
    category: "intelligence",
    isCore: false,
    defaultEnabled: false,
    navLinkIds: [],
    aiToolNames: ["run_business_pulse"],
    routes: [],
    setupChecks: [],
    docsUrl:
      "https://github.com/JohnConnorCode/accelerate-site/blob/main/plugins/business-pulse/README.md",
    report: {
      version: 1,
      sources: [
        {
          name: "pipeline",
          type: "report_opportunities",
          columns: ["id", "name", "stage", "updated_at", "next_action_at"],
        },
        {
          name: "commitments",
          type: "report_tasks",
          columns: ["id", "title", "status", "due_date"],
        },
        {
          name: "meetings",
          type: "report_calendar_events",
          columns: ["id", "title", "status", "start_at", "end_at"],
        },
      ],
    },
  },
  {
    id: "client-onboarding",
    name: "Client onboarding",
    description:
      "Turn a won deal into an assigned, dated delivery checklist with durable task receipts.",
    category: "delivery",
    isCore: false,
    defaultEnabled: false,
    navLinkIds: ["client-onboarding"],
    aiToolNames: ["prepare_client_onboarding", "propose_client_onboarding"],
    routes: ["/admin/client-onboarding"],
    setupChecks: [],
    docsUrl:
      "https://github.com/JohnConnorCode/accelerate-site/blob/main/plugins/client-onboarding/README.md",
    workflow: {
      version: 1,
      inputSchema: {
        type: "object",
        properties: {
          opportunityId: {
            type: "string",
            maxLength: 36,
            minLength: 36,
          },
          tasks: {
            minItems: 1,
            maxItems: 10,
            type: "array",
            items: {
              type: "object",
              properties: {
                title: {
                  type: "string",
                  minLength: 1,
                  maxLength: 200,
                },
                description: {
                  type: "string",
                  maxLength: 2000,
                },
                dueDate: {
                  type: "string",
                  maxLength: 10,
                  minLength: 10,
                },
                assigneeUserId: {
                  type: "string",
                  maxLength: 36,
                  minLength: 36,
                },
              },
              required: ["title", "description", "dueDate", "assigneeUserId"],
              additionalProperties: false,
            },
          },
        },
        required: ["opportunityId", "tasks"],
        additionalProperties: false,
      },
      actions: ["create_task_batch"],
      sources: [
        {
          name: "opportunity",
          type: "workflow_opportunities",
          columns: ["id", "name", "stage"],
          inputKey: "opportunityId",
        },
      ],
      inputContract: "task-batch-opportunity-v1",
      policy: {
        version: 1,
        action: "create_task_batch",
        trustCeiling: "always-propose",
        evidence: {
          kind: "canonical-record",
          inputKey: "opportunityId",
          sourceType: "workflow_opportunities",
        },
        idempotency: {
          request: "workflow-request-v1",
          effect: "task-content-sha256-v1",
        },
        tier: 2,
        impact: "internal_write",
        reversibility: "compensable",
      },
      contractHash: "58b9ecdf5066879da8cd0a47d60d89de56c8ef0fc107c4dbba5337dac1751a97",
      tools: [
        {
          operation: "prepare-workflow",
          name: "prepare_client_onboarding",
          description:
            "Prepare Client onboarding: Turn a won deal into an assigned, dated delivery checklist with durable task receipts.. Returns a reviewable plan, never executes it.",
          serviceTarget: "revenue-os.workflow-plugins",
          connectionRequirement: "none",
          impact: "read",
          confirmationRequired: false,
          inputSchema: {
            $schema: "http://json-schema.org/draft-07/schema#",
            type: "object",
            properties: {
              opportunityId: {
                type: "string",
                format: "uuid",
                pattern:
                  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
              },
              tasks: {
                minItems: 1,
                maxItems: 10,
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    title: {
                      type: "string",
                      minLength: 1,
                      maxLength: 200,
                    },
                    description: {
                      type: "string",
                      maxLength: 2000,
                    },
                    dueDate: {
                      type: "string",
                      format: "date",
                      pattern:
                        "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))$",
                    },
                    assigneeUserId: {
                      type: "string",
                      format: "uuid",
                      pattern:
                        "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
                    },
                  },
                  required: ["title", "description", "dueDate", "assigneeUserId"],
                  additionalProperties: false,
                },
              },
            },
            required: ["opportunityId", "tasks"],
            additionalProperties: false,
          },
        },
        {
          operation: "propose-workflow",
          name: "propose_client_onboarding",
          description:
            "Stage the exact previewed Client onboarding for human approval. Use its digest and a stable UUID requestId. Never executes the action.",
          serviceTarget: "revenue-os.workflow-plugins",
          connectionRequirement: "none",
          impact: "internal_write",
          confirmationRequired: true,
          inputSchema: {
            $schema: "http://json-schema.org/draft-07/schema#",
            type: "object",
            properties: {
              input: {
                type: "object",
                properties: {
                  opportunityId: {
                    type: "string",
                    format: "uuid",
                    pattern:
                      "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
                  },
                  tasks: {
                    minItems: 1,
                    maxItems: 10,
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        title: {
                          type: "string",
                          minLength: 1,
                          maxLength: 200,
                        },
                        description: {
                          type: "string",
                          maxLength: 2000,
                        },
                        dueDate: {
                          type: "string",
                          format: "date",
                          pattern:
                            "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))$",
                        },
                        assigneeUserId: {
                          type: "string",
                          format: "uuid",
                          pattern:
                            "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
                        },
                      },
                      required: ["title", "description", "dueDate", "assigneeUserId"],
                      additionalProperties: false,
                    },
                  },
                },
                required: ["opportunityId", "tasks"],
                additionalProperties: false,
              },
              digest: {
                type: "string",
                pattern: "^[a-f0-9]{64}$",
              },
              requestId: {
                type: "string",
                format: "uuid",
                pattern:
                  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
              },
            },
            required: ["input", "digest", "requestId"],
            additionalProperties: false,
          },
        },
      ],
    },
  },
  {
    id: "commitment-watch",
    name: "Overdue commitments",
    description: "Find unfinished tasks whose due date has passed.",
    category: "intelligence",
    isCore: false,
    defaultEnabled: false,
    navLinkIds: [],
    aiToolNames: ["run_commitment_watch"],
    routes: [],
    setupChecks: [],
    docsUrl:
      "https://github.com/JohnConnorCode/accelerate-site/blob/main/plugins/commitment-watch/README.md",
    report: {
      version: 1,
      sources: [
        {
          name: "records",
          type: "report_tasks",
          columns: ["id", "title", "status", "due_date"],
        },
      ],
    },
  },
  {
    id: "example-inventory",
    name: "Inventory (example)",
    description:
      "A complete, minimal example manifest showing every field an extension module can declare. Disabled by default so it never appears in a real workspace unless a self-hoster turns it on.",
    category: "delivery",
    isCore: false,
    defaultEnabled: false,
    navLinkIds: ["example-inventory"],
    aiToolNames: [],
    routes: ["/admin/example-inventory"],
    setupChecks: [],
    docsUrl:
      "https://github.com/JohnConnorCode/accelerate-site/blob/main/plugins/example-inventory/README.md",
    settings: [
      {
        key: "reorderThreshold",
        label: "Reorder threshold",
        description: "Flag an item as low stock once its quantity falls to or below this number.",
        type: "number",
        default: 10,
        min: 0,
        max: 10000,
      },
      {
        key: "defaultWarehouse",
        label: "Default warehouse",
        description: "Where a newly received item is assumed to be stored.",
        type: "enum",
        options: ["main", "overflow"],
        default: "main",
      },
      {
        key: "autoReorderEnabled",
        label: "Propose reorders automatically",
        description:
          "When on, low-stock items get a reorder task proposed for approval instead of waiting to be noticed.",
        type: "boolean",
        default: false,
      },
    ],
  },
  {
    id: "meeting-commitments",
    name: "Meeting commitments",
    description:
      "Turn reviewed meeting commitments into assigned follow-ups linked to the meeting.",
    category: "delivery",
    isCore: false,
    defaultEnabled: false,
    navLinkIds: ["meeting-commitments"],
    aiToolNames: ["prepare_meeting_commitments", "propose_meeting_commitments"],
    routes: ["/admin/meeting-commitments"],
    setupChecks: [],
    docsUrl:
      "https://github.com/JohnConnorCode/accelerate-site/blob/main/plugins/meeting-commitments/README.md",
    workflow: {
      version: 1,
      inputSchema: {
        type: "object",
        properties: {
          meetingId: {
            type: "string",
            maxLength: 36,
            minLength: 36,
          },
          tasks: {
            minItems: 1,
            maxItems: 10,
            type: "array",
            items: {
              type: "object",
              properties: {
                title: {
                  type: "string",
                  minLength: 1,
                  maxLength: 200,
                },
                description: {
                  type: "string",
                  maxLength: 2000,
                },
                dueDate: {
                  type: "string",
                  maxLength: 10,
                  minLength: 10,
                },
                assigneeUserId: {
                  type: "string",
                  maxLength: 36,
                  minLength: 36,
                },
              },
              required: ["title", "description", "dueDate", "assigneeUserId"],
              additionalProperties: false,
            },
          },
        },
        required: ["meetingId", "tasks"],
        additionalProperties: false,
      },
      actions: ["create_task_batch"],
      sources: [
        {
          name: "meeting",
          type: "workflow_meetings",
          columns: ["id", "title", "start_at"],
          inputKey: "meetingId",
        },
      ],
      inputContract: "task-batch-meeting-v1",
      policy: {
        version: 1,
        action: "create_task_batch",
        trustCeiling: "always-propose",
        evidence: {
          kind: "canonical-record",
          inputKey: "meetingId",
          sourceType: "workflow_meetings",
        },
        idempotency: {
          request: "workflow-request-v1",
          effect: "task-content-sha256-v1",
        },
        tier: 2,
        impact: "internal_write",
        reversibility: "compensable",
      },
      contractHash: "becfce86012d40a47ef39a1410285d22faf50e972a42d0b67497cc2b16313ada",
      tools: [
        {
          operation: "prepare-workflow",
          name: "prepare_meeting_commitments",
          description:
            "Prepare Meeting commitments: Turn reviewed meeting commitments into assigned follow-ups linked to the meeting.. Returns a reviewable plan, never executes it.",
          serviceTarget: "revenue-os.workflow-plugins",
          connectionRequirement: "none",
          impact: "read",
          confirmationRequired: false,
          inputSchema: {
            $schema: "http://json-schema.org/draft-07/schema#",
            type: "object",
            properties: {
              meetingId: {
                type: "string",
                format: "uuid",
                pattern:
                  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
              },
              tasks: {
                minItems: 1,
                maxItems: 10,
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    title: {
                      type: "string",
                      minLength: 1,
                      maxLength: 200,
                    },
                    description: {
                      type: "string",
                      maxLength: 2000,
                    },
                    dueDate: {
                      type: "string",
                      format: "date",
                      pattern:
                        "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))$",
                    },
                    assigneeUserId: {
                      type: "string",
                      format: "uuid",
                      pattern:
                        "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
                    },
                  },
                  required: ["title", "description", "dueDate", "assigneeUserId"],
                  additionalProperties: false,
                },
              },
            },
            required: ["meetingId", "tasks"],
            additionalProperties: false,
          },
        },
        {
          operation: "propose-workflow",
          name: "propose_meeting_commitments",
          description:
            "Stage the exact previewed Meeting commitments for human approval. Use its digest and a stable UUID requestId. Never executes the action.",
          serviceTarget: "revenue-os.workflow-plugins",
          connectionRequirement: "none",
          impact: "internal_write",
          confirmationRequired: true,
          inputSchema: {
            $schema: "http://json-schema.org/draft-07/schema#",
            type: "object",
            properties: {
              input: {
                type: "object",
                properties: {
                  meetingId: {
                    type: "string",
                    format: "uuid",
                    pattern:
                      "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
                  },
                  tasks: {
                    minItems: 1,
                    maxItems: 10,
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        title: {
                          type: "string",
                          minLength: 1,
                          maxLength: 200,
                        },
                        description: {
                          type: "string",
                          maxLength: 2000,
                        },
                        dueDate: {
                          type: "string",
                          format: "date",
                          pattern:
                            "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))$",
                        },
                        assigneeUserId: {
                          type: "string",
                          format: "uuid",
                          pattern:
                            "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
                        },
                      },
                      required: ["title", "description", "dueDate", "assigneeUserId"],
                      additionalProperties: false,
                    },
                  },
                },
                required: ["meetingId", "tasks"],
                additionalProperties: false,
              },
              digest: {
                type: "string",
                pattern: "^[a-f0-9]{64}$",
              },
              requestId: {
                type: "string",
                format: "uuid",
                pattern:
                  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
              },
            },
            required: ["input", "digest", "requestId"],
            additionalProperties: false,
          },
        },
      ],
    },
  },
  {
    id: "meeting-prep",
    name: "Meeting preparation",
    description: "Prepare a factual agenda of stored meetings in the next 48 hours.",
    category: "intelligence",
    isCore: false,
    defaultEnabled: false,
    navLinkIds: [],
    aiToolNames: ["run_meeting_prep"],
    routes: [],
    setupChecks: [],
    docsUrl:
      "https://github.com/JohnConnorCode/accelerate-site/blob/main/plugins/meeting-prep/README.md",
    report: {
      version: 1,
      sources: [
        {
          name: "records",
          type: "report_calendar_events",
          columns: ["id", "title", "status", "start_at", "end_at"],
        },
      ],
    },
  },
  {
    id: "opportunity-radar",
    name: "Opportunity Radar",
    description:
      "Keep versioned sources, reviewed growth opportunities and drafts, with bounded AI source briefing. Automated discovery, outreach and publication are not yet available.",
    category: "intelligence",
    isCore: false,
    defaultEnabled: false,
    navLinkIds: ["opportunity-radar"],
    aiToolNames: [
      "get_radar_workspace",
      "prepare_radar_opportunity_brief",
      "prepare_radar_brief",
      "get_radar_model_status",
      "reconcile_radar_model_call",
      "get_radar_store",
      "preview_radar_store_change",
      "propose_radar_store_change",
      "get_radar_selection",
      "preview_radar_assessment",
      "propose_radar_assessment",
    ],
    routes: ["/admin/radar"],
    historyRoute: "/admin/radar/history",
    setupChecks: [],
    docsUrl:
      "https://github.com/JohnConnorCode/accelerate-site/blob/main/plugins/opportunity-radar/README.md",
    settings: [
      {
        key: "organization",
        label: "Organization",
        description: "Your public business or project name.",
        type: "string",
        default: "",
      },
      {
        key: "website",
        label: "Website",
        description: "Your public HTTPS website. This setting does not authorize fetching URLs.",
        type: "url",
        default: "",
      },
      {
        key: "spokesperson",
        label: "Spokesperson",
        description: "Optional public representative; leave blank for organization-only work.",
        type: "string",
        default: "",
      },
      {
        key: "mission",
        label: "Mission and offer",
        description: "What you do and the useful contribution you can make.",
        type: "string",
        default: "",
      },
      {
        key: "expertise",
        label: "Earned expertise",
        description:
          "Firsthand experience you can substantiate; do not enter unsupported credentials.",
        type: "string",
        default: "",
      },
      {
        key: "audiences",
        label: "Business audiences",
        description: "The customers, professional communities or institutions you serve.",
        type: "string",
        default: "",
      },
      {
        key: "topics",
        label: "Topics",
        description:
          "Business topics to watch. Public affairs requires separate neutral review, not growth scoring.",
        type: "string",
        default: "",
      },
      {
        key: "ownedAssets",
        label: "Public assets",
        description:
          "Public URLs/descriptions, one per line. These are owned resources, not independent coverage.",
        type: "string",
        default: "",
      },
      {
        key: "region",
        label: "Region",
        description: "Geographic focus, or leave blank for no regional restriction.",
        type: "string",
        default: "",
      },
      {
        key: "timeZone",
        label: "Time zone",
        description:
          "IANA time zone, such as America/Chicago. Scheduling is not active in this foundation.",
        type: "string",
        default: "UTC",
      },
      {
        key: "dailyShortlist",
        label: "Daily shortlist limit",
        description: "Maximum reviewed business recommendations returned by daily selection.",
        type: "number",
        min: 1,
        max: 10,
        default: 5,
      },
      {
        key: "maxDiscoveries",
        label: "Daily discovery limit",
        description: "Future worker cap; this does not start discovery.",
        type: "number",
        min: 1,
        max: 500,
        default: 50,
      },
      {
        key: "dailyModelBudgetUsd",
        label: "Daily model budget (USD)",
        description:
          "Zero disables automatic model spending. Model jobs must reserve the budget before calls.",
        type: "number",
        min: 0,
        max: 100,
        default: 0,
      },
      {
        key: "modelMode",
        label: "Model spending mode",
        type: "enum",
        options: ["off", "free-only", "budgeted-low-cost"],
        default: "off",
        description:
          "Applies to source briefing jobs. Off makes no model calls; free-only must never fall back to paid models.",
      },
      {
        key: "preferredModel",
        label: "Preferred registered model",
        type: "string",
        default: "",
        description:
          "Explicit model ID from the shared evaluated model registry. OpenRouter is the current transport; no premium default or invented model IDs.",
      },
      {
        key: "maxModelCallsPerDay",
        label: "Daily model call limit",
        type: "number",
        min: 0,
        max: 20,
        default: 0,
        description:
          "Independent call cap, including free models and retries. Zero disables automatic model calls.",
      },
      {
        key: "maxInputTokensPerCall",
        label: "Input token limit per call",
        type: "number",
        min: 1024,
        max: 16000,
        default: 8000,
        description: "Bound retrieved evidence before a model request.",
      },
      {
        key: "maxOutputTokensPerCall",
        label: "Output token limit per call",
        type: "number",
        min: 256,
        max: 4000,
        default: 1000,
        description: "Short structured results; no unbounded drafting loops.",
      },
      {
        key: "maxCostPerRunUsd",
        label: "Maximum cost per run (USD)",
        type: "number",
        min: 0,
        max: 1,
        default: 0,
        description:
          "Model jobs reserve worst-case cost before requests; zero allows no paid request.",
      },
      {
        key: "sourceMode",
        label: "Source mode",
        type: "enum",
        options: ["free-first"],
        default: "free-first",
        description: "No paid-source activation. Available public sources still have usage limits.",
      },
      {
        key: "outreachMode",
        label: "Outreach mode",
        type: "enum",
        options: ["draft-only"],
        default: "draft-only",
        description: "No sending or publication is enabled by setup.",
      },
    ],
    settingsContract: "opportunity-radar-profile-v1",
  },
  {
    id: "pipeline-watch",
    name: "Pipeline follow-up",
    description: "Find open opportunities with an overdue next action or no update in seven days.",
    category: "intelligence",
    isCore: false,
    defaultEnabled: false,
    navLinkIds: [],
    aiToolNames: ["run_pipeline_watch"],
    routes: [],
    setupChecks: [],
    docsUrl:
      "https://github.com/JohnConnorCode/accelerate-site/blob/main/plugins/pipeline-watch/README.md",
    report: {
      version: 1,
      sources: [
        {
          name: "records",
          type: "report_opportunities",
          columns: ["id", "name", "stage", "updated_at", "next_action_at"],
        },
      ],
    },
  },
  {
    id: "receivables-collections",
    name: "Collections Action Desk",
    description:
      "Track verified overdue invoices, disputes, payment promises and collection follow-up for CRM billing contacts.",
    category: "revenue",
    isCore: false,
    defaultEnabled: false,
    navLinkIds: ["receivables-collections"],
    aiToolNames: [
      "get_collection_cases",
      "preview_collection_reminder",
      "propose_collection_reminder",
    ],
    routes: ["/admin/collections"],
    setupChecks: [],
    docsUrl:
      "https://github.com/JohnConnorCode/accelerate-site/blob/main/plugins/receivables-collections/README.md",
    settings: [
      {
        key: "cooldownHours",
        label: "Reminder cooldown (hours)",
        description: "Minimum time between confirmed reminder sends for an account and currency.",
        type: "number",
        default: 72,
        min: 1,
        max: 720,
      },
    ],
  },
  {
    id: "stripe-invoicing",
    name: "Stripe invoicing",
    description:
      "Create reviewed invoices for CRM customers, approve sending, and track Stripe payment status.",
    category: "revenue",
    isCore: false,
    defaultEnabled: false,
    navLinkIds: ["stripe-invoicing"],
    aiToolNames: [
      "prepare_stripe_invoicing",
      "propose_stripe_invoicing",
      "propose_stripe_invoice_send",
      "preview_invoice_page",
      "propose_invoice_page",
    ],
    routes: ["/admin/invoicing"],
    setupChecks: [],
    docsUrl:
      "https://github.com/JohnConnorCode/accelerate-site/blob/main/plugins/stripe-invoicing/README.md",
    workflow: {
      version: 1,
      inputSchema: {
        type: "object",
        properties: {
          contactId: {
            type: "string",
            maxLength: 36,
            minLength: 36,
          },
          customerId: {
            type: "string",
            minLength: 5,
            maxLength: 84,
          },
          currency: {
            type: "string",
            enum: ["usd", "eur", "gbp", "cad", "aud"],
          },
          daysUntilDue: {
            type: "integer",
            minimum: 1,
            maximum: 90,
          },
          memo: {
            type: "string",
            maxLength: 500,
          },
          lines: {
            minItems: 1,
            maxItems: 10,
            type: "array",
            items: {
              type: "object",
              properties: {
                description: {
                  type: "string",
                  minLength: 1,
                  maxLength: 200,
                },
                quantity: {
                  type: "integer",
                  minimum: 1,
                  maximum: 10000,
                },
                unitAmount: {
                  type: "integer",
                  minimum: 1,
                  maximum: 100000000,
                },
              },
              required: ["description", "quantity", "unitAmount"],
              additionalProperties: false,
            },
          },
        },
        required: ["contactId", "customerId", "currency", "daysUntilDue", "memo", "lines"],
        additionalProperties: false,
      },
      actions: ["create_stripe_invoice_draft"],
      sources: [
        {
          name: "contact",
          type: "workflow_contacts",
          columns: ["id", "full_name", "primary_email"],
          inputKey: "contactId",
        },
      ],
      inputContract: "stripe-invoice-draft-v1",
      policy: {
        version: 1,
        action: "create_stripe_invoice_draft",
        trustCeiling: "always-propose",
        evidence: {
          kind: "canonical-record",
          inputKey: "contactId",
          sourceType: "workflow_contacts",
        },
        idempotency: {
          request: "workflow-request-v1",
          effect: "stripe-action-v1",
        },
        tier: 3,
        impact: "external_action",
        reversibility: "irreversible",
      },
      contractHash: "ebeae760413591942ebc252183497b80624a3ba636fd1806ce426b8286e201db",
      tools: [
        {
          operation: "prepare-workflow",
          name: "prepare_stripe_invoicing",
          description:
            "Prepare Stripe invoicing: Create reviewed invoices for CRM customers, approve sending, and track Stripe payment status.. Returns a reviewable plan, never executes it.",
          serviceTarget: "revenue-os.workflow-plugins",
          connectionRequirement: "none",
          impact: "read",
          confirmationRequired: false,
          inputSchema: {
            $schema: "http://json-schema.org/draft-07/schema#",
            type: "object",
            properties: {
              contactId: {
                type: "string",
                format: "uuid",
                pattern:
                  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
              },
              customerId: {
                type: "string",
                minLength: 5,
                maxLength: 84,
                pattern: "^cus_[A-Za-z0-9]{1,80}$",
              },
              currency: {
                type: "string",
                enum: ["usd", "eur", "gbp", "cad", "aud"],
              },
              daysUntilDue: {
                type: "integer",
                minimum: 1,
                maximum: 90,
              },
              memo: {
                type: "string",
                maxLength: 500,
              },
              lines: {
                minItems: 1,
                maxItems: 10,
                type: "array",
                items: {
                  type: "object",
                  properties: {
                    description: {
                      type: "string",
                      minLength: 1,
                      maxLength: 200,
                    },
                    quantity: {
                      type: "integer",
                      minimum: 1,
                      maximum: 10000,
                    },
                    unitAmount: {
                      type: "integer",
                      minimum: 1,
                      maximum: 100000000,
                    },
                  },
                  required: ["description", "quantity", "unitAmount"],
                  additionalProperties: false,
                },
              },
            },
            required: ["contactId", "customerId", "currency", "daysUntilDue", "memo", "lines"],
            additionalProperties: false,
          },
        },
        {
          operation: "propose-workflow",
          name: "propose_stripe_invoicing",
          description:
            "Stage the exact previewed Stripe invoicing for human approval. Use its digest and a stable UUID requestId. Never executes the action.",
          serviceTarget: "revenue-os.workflow-plugins",
          connectionRequirement: "none",
          impact: "internal_write",
          confirmationRequired: true,
          inputSchema: {
            $schema: "http://json-schema.org/draft-07/schema#",
            type: "object",
            properties: {
              input: {
                type: "object",
                properties: {
                  contactId: {
                    type: "string",
                    format: "uuid",
                    pattern:
                      "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
                  },
                  customerId: {
                    type: "string",
                    minLength: 5,
                    maxLength: 84,
                    pattern: "^cus_[A-Za-z0-9]{1,80}$",
                  },
                  currency: {
                    type: "string",
                    enum: ["usd", "eur", "gbp", "cad", "aud"],
                  },
                  daysUntilDue: {
                    type: "integer",
                    minimum: 1,
                    maximum: 90,
                  },
                  memo: {
                    type: "string",
                    maxLength: 500,
                  },
                  lines: {
                    minItems: 1,
                    maxItems: 10,
                    type: "array",
                    items: {
                      type: "object",
                      properties: {
                        description: {
                          type: "string",
                          minLength: 1,
                          maxLength: 200,
                        },
                        quantity: {
                          type: "integer",
                          minimum: 1,
                          maximum: 10000,
                        },
                        unitAmount: {
                          type: "integer",
                          minimum: 1,
                          maximum: 100000000,
                        },
                      },
                      required: ["description", "quantity", "unitAmount"],
                      additionalProperties: false,
                    },
                  },
                },
                required: ["contactId", "customerId", "currency", "daysUntilDue", "memo", "lines"],
                additionalProperties: false,
              },
              digest: {
                type: "string",
                pattern: "^[a-f0-9]{64}$",
              },
              requestId: {
                type: "string",
                format: "uuid",
                pattern:
                  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
              },
            },
            required: ["input", "digest", "requestId"],
            additionalProperties: false,
          },
        },
        {
          operation: "propose-invoice-send",
          name: "propose_stripe_invoice_send",
          description:
            "Stage sending an existing completed Stripe invoice for explicit human approval. Does not send it.",
          serviceTarget: "revenue-os.stripe-invoicing",
          connectionRequirement: "none",
          impact: "internal_write",
          confirmationRequired: true,
          inputSchema: {
            $schema: "http://json-schema.org/draft-07/schema#",
            type: "object",
            properties: {
              creationActionId: {
                type: "string",
                format: "uuid",
                pattern:
                  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
              },
            },
            required: ["creationActionId"],
            additionalProperties: false,
          },
        },
        {
          operation: "preview-invoice-page",
          name: "preview_invoice_page",
          description:
            "Preview a bounded customer invoice design using workspace branding and authoritative Stripe billing facts. Returns the publication digest; does not publish.",
          serviceTarget: "revenue-os.invoice-pages",
          connectionRequirement: "none",
          impact: "read",
          confirmationRequired: false,
          inputSchema: {
            $schema: "http://json-schema.org/draft-07/schema#",
            type: "object",
            properties: {
              creationActionId: {
                type: "string",
                format: "uuid",
                pattern:
                  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
              },
              design: {
                type: "object",
                properties: {
                  layout: {
                    type: "string",
                    enum: ["classic", "editorial"],
                  },
                  heading: {
                    type: "string",
                    minLength: 1,
                    maxLength: 80,
                  },
                  introduction: {
                    type: "string",
                    maxLength: 500,
                  },
                  closing: {
                    type: "string",
                    maxLength: 300,
                  },
                },
                required: ["layout", "heading", "introduction", "closing"],
                additionalProperties: false,
              },
            },
            required: ["creationActionId", "design"],
            additionalProperties: false,
          },
        },
        {
          operation: "propose-invoice-page",
          name: "propose_invoice_page",
          description:
            "Stage the exact previewed invoice page for human publication approval. Does not publish or email the customer.",
          serviceTarget: "revenue-os.invoice-pages",
          connectionRequirement: "none",
          impact: "internal_write",
          confirmationRequired: true,
          inputSchema: {
            $schema: "http://json-schema.org/draft-07/schema#",
            type: "object",
            properties: {
              creationActionId: {
                type: "string",
                format: "uuid",
                pattern:
                  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
              },
              design: {
                type: "object",
                properties: {
                  layout: {
                    type: "string",
                    enum: ["classic", "editorial"],
                  },
                  heading: {
                    type: "string",
                    minLength: 1,
                    maxLength: 80,
                  },
                  introduction: {
                    type: "string",
                    maxLength: 500,
                  },
                  closing: {
                    type: "string",
                    maxLength: 300,
                  },
                },
                required: ["layout", "heading", "introduction", "closing"],
                additionalProperties: false,
              },
              digest: {
                type: "string",
                pattern: "^[a-f0-9]{64}$",
              },
              requestId: {
                type: "string",
                format: "uuid",
                pattern:
                  "^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$",
              },
            },
            required: ["creationActionId", "design", "digest", "requestId"],
            additionalProperties: false,
          },
        },
      ],
    },
  },
] as const;

export const EXTENSION_NAV_LINKS: readonly ExtensionNavLink[] = [
  {
    moduleId: "client-onboarding",
    id: "client-onboarding",
    label: "Client onboarding",
    href: "/admin/client-onboarding",
    icon: "ListChecks",
    description:
      "Turn a won deal into an assigned, dated delivery checklist with durable task receipts.",
    moreGroup: "Delivery",
  },
  {
    moduleId: "example-inventory",
    id: "example-inventory",
    label: "Inventory",
    href: "/admin/example-inventory",
    icon: "Library",
    description: "Stock levels and reorder points",
    moreGroup: "Delivery",
  },
  {
    moduleId: "meeting-commitments",
    id: "meeting-commitments",
    label: "Meeting commitments",
    href: "/admin/meeting-commitments",
    icon: "ListChecks",
    description:
      "Turn reviewed meeting commitments into assigned follow-ups linked to the meeting.",
    moreGroup: "Delivery",
  },
  {
    moduleId: "opportunity-radar",
    id: "opportunity-radar",
    label: "Opportunity Radar",
    href: "/admin/radar/today",
    icon: "Radar",
    description: "Sourced business opportunities, research and reviewed actions.",
    moreGroup: "Intelligence",
  },
  {
    moduleId: "receivables-collections",
    id: "receivables-collections",
    label: "Collections",
    href: "/admin/collections",
    icon: "Wallet",
    description: "Resolve overdue balances and review reminders",
    moreGroup: "Revenue",
  },
  {
    moduleId: "stripe-invoicing",
    id: "stripe-invoicing",
    label: "Invoicing",
    href: "/admin/invoicing",
    icon: "FileText",
    description: "Customer invoices and payment status",
    moreGroup: "Revenue",
  },
] as const;
