// Generated by scripts/build-extension-modules.mjs. Do not edit by hand.
// Source of truth: extensions/*.module.json. Run `npm run build:extensions`
// after changing a manifest; CI fails if this file drifts from the manifests.
import type { RevenueOSModule } from "./modules";

/** Nav link icon names are validated against an allowlist at build time and
 *  resolved to components in src/lib/admin/extension-nav-icons.ts. */
export interface ExtensionNavLink {
  moduleId: string;
  id: string;
  label: string;
  href: string;
  icon: string;
  description: string;
  keywords?: string;
  moreGroup?: "Revenue" | "Delivery" | "Intelligence" | "System" | "Sources";
}

export const EXTENSION_MODULES: readonly RevenueOSModule[] = [
  {
    id: "business-pulse",
    name: "Business pulse",
    description:
      "Bring pipeline risks, overdue commitments and upcoming meetings into one factual briefing.",
    category: "intelligence",
    isCore: false,
    defaultEnabled: false,
    navLinkIds: [],
    aiToolNames: ["run_business_pulse"],
    routes: [],
    setupChecks: [],
    report: {
      version: 1,
      sources: [
        {
          name: "pipeline",
          type: "report_opportunities",
          columns: ["id", "name", "stage", "updated_at", "next_action_at"],
        },
        {
          name: "commitments",
          type: "report_tasks",
          columns: ["id", "title", "status", "due_date"],
        },
        {
          name: "meetings",
          type: "report_calendar_events",
          columns: ["id", "title", "status", "start_at", "end_at"],
        },
      ],
    },
  },
  {
    id: "commitment-watch",
    name: "Overdue commitments",
    description: "Find unfinished tasks whose due date has passed.",
    category: "intelligence",
    isCore: false,
    defaultEnabled: false,
    navLinkIds: [],
    aiToolNames: ["run_commitment_watch"],
    routes: [],
    setupChecks: [],
    report: {
      version: 1,
      sources: [
        {
          name: "records",
          type: "report_tasks",
          columns: ["id", "title", "status", "due_date"],
        },
      ],
    },
  },
  {
    id: "example-inventory",
    name: "Inventory (example)",
    description:
      "A complete, minimal example manifest showing every field an extension module can declare. Disabled by default so it never appears in a real workspace unless a self-hoster turns it on.",
    category: "delivery",
    isCore: false,
    defaultEnabled: false,
    navLinkIds: ["example-inventory"],
    aiToolNames: [],
    routes: ["/admin/example-inventory"],
    setupChecks: [],
    docsUrl:
      "https://github.com/JohnConnorCode/accelerate-site/blob/main/docs/contributing/EXTENDING.md",
    settings: [
      {
        key: "reorderThreshold",
        label: "Reorder threshold",
        description: "Flag an item as low stock once its quantity falls to or below this number.",
        type: "number",
        default: 10,
        min: 0,
        max: 10000,
      },
      {
        key: "defaultWarehouse",
        label: "Default warehouse",
        description: "Where a newly received item is assumed to be stored.",
        type: "enum",
        options: ["main", "overflow"],
        default: "main",
      },
      {
        key: "autoReorderEnabled",
        label: "Propose reorders automatically",
        description:
          "When on, low-stock items get a reorder task proposed for approval instead of waiting to be noticed.",
        type: "boolean",
        default: false,
      },
    ],
  },
  {
    id: "meeting-prep",
    name: "Meeting preparation",
    description: "Prepare a factual agenda of stored meetings in the next 48 hours.",
    category: "intelligence",
    isCore: false,
    defaultEnabled: false,
    navLinkIds: [],
    aiToolNames: ["run_meeting_prep"],
    routes: [],
    setupChecks: [],
    report: {
      version: 1,
      sources: [
        {
          name: "records",
          type: "report_calendar_events",
          columns: ["id", "title", "status", "start_at", "end_at"],
        },
      ],
    },
  },
  {
    id: "pipeline-watch",
    name: "Pipeline follow-up",
    description: "Find open opportunities with an overdue next action or no update in seven days.",
    category: "intelligence",
    isCore: false,
    defaultEnabled: false,
    navLinkIds: [],
    aiToolNames: ["run_pipeline_watch"],
    routes: [],
    setupChecks: [],
    report: {
      version: 1,
      sources: [
        {
          name: "records",
          type: "report_opportunities",
          columns: ["id", "name", "stage", "updated_at", "next_action_at"],
        },
      ],
    },
  },
] as const;

export const EXTENSION_NAV_LINKS: readonly ExtensionNavLink[] = [
  {
    moduleId: "example-inventory",
    id: "example-inventory",
    label: "Inventory",
    href: "/admin/example-inventory",
    icon: "Library",
    description: "Stock levels and reorder points",
    moreGroup: "Delivery",
  },
] as const;
