"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowUpRight, BookmarkPlus, Building2, Check, CircleDollarSign, Columns3, List, Loader2, Plus, RefreshCw, Search, Settings2, Target, Trash2, TriangleAlert, X } from "lucide-react";
import { AdminDialog } from "@/components/admin/AdminDialog";
import { AdminSurface } from "@/components/admin/AdminSurface";
import { PageHeader } from "@/components/admin/PageHeader";
import { RevenueSetupGate } from "@/components/admin/RevenueSetupGate";
import { fetchJson } from "@/lib/admin/fetchJson";
import { DEFAULT_PIPELINE_VIEW, PIPELINE_VISIBLE_FIELDS, SYSTEM_PIPELINE_VIEWS, applyPipelineView, countPipelineSystemViews, loadLastPipelineView, loadSavedPipelineViews, removePipelineView, saveLastPipelineView, savePipelineView, type PipelineViewState, type PipelineVisibleField, type SavedPipelineView } from "@/lib/admin/pipelineViews";
import { REVENUE_STAGE_META, REVENUE_STAGES, type RevenueStage } from "@/lib/revenue-os/types";
import { cn } from "@/lib/utils";

interface Opportunity {
  id: string; name: string | null; email: string | null; stage: string; canonical_stage: RevenueStage | null;
  estimated_value: number; won_value: number; next_action: string | null; next_action_at: string | null; source: string | null;
  owner_email?: string | null; last_activity_at?: string | null; next_meeting_at?: string | null; closed_at?: string | null; updated_at?: string | null; created_at: string;
  contact?: { full_name: string; primary_email: string | null } | null;
  company?: { name: string; domain: string | null; industry: string | null } | null;
}

const tones: Record<RevenueStage, string> = {
  new: "bg-black/[0.05] text-[var(--admin-muted)] dark:bg-white/[0.07]", contacted: "bg-blue-500/10 text-blue-700 dark:text-blue-300", qualified: "bg-cyan-500/10 text-cyan-700 dark:text-cyan-300", meeting: "bg-amber-500/12 text-amber-800 dark:text-amber-300", proposal: "bg-violet-500/10 text-violet-700 dark:text-violet-300", negotiation: "bg-fuchsia-500/10 text-fuchsia-700 dark:text-fuchsia-300", won: "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300", lost: "bg-rose-500/10 text-rose-700 dark:text-rose-300", nurture: "bg-slate-500/10 text-slate-700 dark:text-slate-300",
};
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value || 0);
const shortDate = (value?: string | null) => value ? new Date(value).toLocaleDateString(undefined, { month: "short", day: "numeric" }) : "No date";
const has = (state: PipelineViewState, field: PipelineVisibleField) => state.visibleFields.includes(field);

export default function PipelinePage() {
  const [data, setData] = useState<{ schemaReady: boolean; signalsReady?: { calendar: boolean }; opportunities: Opportunity[] } | null>(null);
  const [state, setState] = useState<PipelineViewState>(DEFAULT_PIPELINE_VIEW);
  const [saved, setSaved] = useState<SavedPipelineView[]>([]);
  const [activeSaved, setActiveSaved] = useState<string | null>(null);
  const [ready, setReady] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [dialog, setDialog] = useState<"create" | "customize" | "save" | null>(null);
  const [viewName, setViewName] = useState("");
  const patchState = (patch: Partial<PipelineViewState>) => { setActiveSaved(null); setState((current) => ({ ...current, ...patch })); };
  const load = useCallback(async () => { setError(""); try { setData(await fetchJson("/api/admin/revenue-os/pipeline")); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load pipeline."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => {
    const restored = loadLastPipelineView();
    const params = new URLSearchParams(window.location.search);
    const query = params.get("opportunity")?.trim() || params.get("search")?.trim();
    setState(query ? { ...restored, systemView: "all", stage: "all", owner: "all", search: query } : restored);
    setSaved(loadSavedPipelineViews()); setReady(true);
  }, []);
  useEffect(() => { if (ready) saveLastPipelineView(state); }, [ready, state]);

  const items = useMemo(() => data?.opportunities ?? [], [data]);
  const [referenceNow] = useState(() => new Date());
  const shown = useMemo(() => applyPipelineView(items, state, referenceNow), [items, state, referenceNow]);
  const counts = useMemo(() => countPipelineSystemViews(items, referenceNow), [items, referenceNow]);
  const currentView = SYSTEM_PIPELINE_VIEWS.find((item) => item.id === state.systemView) ?? SYSTEM_PIPELINE_VIEWS[0]!;
  const owners = useMemo(() => [...new Set(items.map((item) => item.owner_email || "unassigned"))].sort(), [items]);
  const metrics = useMemo(() => { const open = items.filter((item) => !["won", "lost"].includes(item.canonical_stage ?? item.stage)); return { open: open.length, value: open.reduce((sum, item) => sum + Number(item.estimated_value || 0), 0), proposals: items.filter((item) => ["proposal", "negotiation"].includes(item.canonical_stage ?? item.stage)).length, won: items.reduce((sum, item) => sum + Number(item.won_value || 0), 0) }; }, [items]);
  const groups = useMemo(() => REVENUE_STAGES.map((stage) => { const opportunities = shown.filter((item) => (item.canonical_stage ?? "new") === stage); return { stage, opportunities, total: opportunities.reduce((sum, item) => sum + Number(item.estimated_value || 0), 0) }; }).filter((group) => state.stage === "all" || group.stage === state.stage), [shown, state.stage]);

  const updateStage = async (item: Opportunity, stage: RevenueStage) => {
    const lossReason = stage === "lost" ? window.prompt("Why was this opportunity lost?")?.trim() : undefined;
    if (stage === "lost" && !lossReason) return;
    setSaving(true);
    try { await fetchJson("/api/admin/revenue-os/pipeline", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: item.id, stage, lossReason, reason: "Founder pipeline update" }) }); await load(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Could not move opportunity."); }
    finally { setSaving(false); }
  };
  const create = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setSaving(true);
    try { await fetchJson("/api/admin/revenue-os/pipeline", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); setDialog(null); await load(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Could not create opportunity."); }
    finally { setSaving(false); }
  };
  const storeView = (event: FormEvent) => { event.preventDefault(); const next = savePipelineView(viewName, state); setSaved(next); setActiveSaved(next.find((item) => item.name.toLowerCase() === viewName.trim().toLowerCase())?.id ?? null); setViewName(""); setDialog(null); };

  if (loading && !data) return <div className="grid min-h-[55vh] place-items-center"><Loader2 className="size-6 animate-spin text-[var(--admin-muted)]" /></div>;
  return <div className="space-y-6 pb-10">
    <PageHeader title="Pipeline" subtitle="Prioritize the work that moves revenue, then review every opportunity from one operating view." actions={<><button type="button" onClick={() => void load()} aria-label="Refresh pipeline" className="grid size-11 place-items-center rounded-xl shadow-[var(--admin-shadow-border)] transition-[box-shadow,transform] duration-150 hover:shadow-[var(--admin-shadow-border-hover)] active:scale-[0.96]"><RefreshCw className={cn("size-4", loading && "animate-spin")} /></button><button type="button" onClick={() => setDialog("create")} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[var(--admin-ink)] px-4 text-xs font-semibold text-[var(--admin-surface)] transition-[opacity,transform] duration-150 hover:opacity-85 active:scale-[0.96]"><Plus className="size-4" /> New opportunity</button></>} />
    {error && <AdminSurface tone="attention" className="flex items-center gap-3"><TriangleAlert className="size-5 shrink-0 text-rose-600" /><p className="text-sm">{error}</p></AdminSurface>}
    {data && !data.schemaReady ? <RevenueSetupGate /> : data && <>
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[
        ["Open", metrics.open, "Active opportunities", Target], ["Pipeline value", money(metrics.value), "Unweighted", CircleDollarSign], ["At proposal", metrics.proposals, "Proposal or negotiation", Building2], ["Won revenue", money(metrics.won), "Recorded outcomes", Building2],
      ].map(([label, value, note, Icon]) => { const MetricIcon = Icon as typeof Target; return <AdminSurface key={String(label)} padding="lg"><div className="flex justify-between gap-3"><div><p className="admin-eyebrow">{String(label)}</p><p className="mt-3 text-3xl font-semibold tabular-nums tracking-[-0.045em]">{String(value)}</p><p className="admin-copy mt-1 text-xs">{String(note)}</p></div><span className="grid size-9 place-items-center rounded-xl bg-black/[0.045] dark:bg-white/[0.06]"><MetricIcon className="size-4" /></span></div></AdminSurface>; })}</section>

      <AdminSurface padding="none" className="w-full min-w-0 max-w-full overflow-hidden [contain:inline-size]">
        <div className="border-b border-[var(--admin-border)] p-4 sm:p-5"><div className="flex items-end justify-between gap-4"><div><p className="admin-eyebrow">Operator views</p><h2 className="mt-1 text-balance text-lg font-semibold tracking-[-0.025em]">{currentView.label}</h2><p className="admin-copy mt-1 max-w-2xl text-pretty text-xs">{currentView.description}</p></div><span className="shrink-0 rounded-full bg-black/[0.045] px-2.5 py-1 font-mono text-[10px] tabular-nums text-[var(--admin-muted)] dark:bg-white/[0.06]">{shown.length} shown</span></div>
          <div className="mt-4 flex gap-2 overflow-x-auto pb-1 [scrollbar-width:none]" aria-label="Pipeline operator views">{SYSTEM_PIPELINE_VIEWS.map((view) => <button key={view.id} type="button" aria-pressed={state.systemView === view.id && !activeSaved} onClick={() => patchState({ systemView: view.id })} className={cn("inline-flex min-h-11 shrink-0 items-center gap-2 rounded-xl px-3.5 text-xs font-semibold transition-[background-color,color,box-shadow,transform] duration-150 active:scale-[0.96]", state.systemView === view.id && !activeSaved ? "bg-[var(--admin-ink)] text-[var(--admin-surface)]" : "text-[var(--admin-muted)] shadow-[var(--admin-shadow-border)] hover:text-[var(--admin-ink)] hover:shadow-[var(--admin-shadow-border-hover)]")}><span>{view.label}</span><span className="font-mono text-[9px] tabular-nums opacity-70">{counts[view.id]}</span></button>)}</div>
          {saved.length > 0 && <div className="mt-3 flex flex-wrap items-center gap-2"><span className="admin-eyebrow mr-1">Saved</span>{saved.map((view) => <div key={view.id} className={cn("flex min-h-11 items-center rounded-xl shadow-[var(--admin-shadow-border)]", activeSaved === view.id && "bg-black/[0.045] dark:bg-white/[0.06]")}><button type="button" onClick={() => { setState(view.state); setActiveSaved(view.id); }} className="min-h-11 rounded-l-xl pl-3.5 pr-2 text-xs font-semibold active:scale-[0.96]">{view.name}</button><button type="button" aria-label={`Delete saved view ${view.name}`} onClick={() => { setSaved(removePipelineView(view.id)); if (activeSaved === view.id) setActiveSaved(null); }} className="grid size-11 place-items-center rounded-r-xl text-[var(--admin-muted)] hover:text-rose-600 active:scale-[0.96]"><Trash2 className="size-3.5" /></button></div>)}</div>}
        </div>
        <div className="grid gap-3 p-4 sm:p-5 lg:grid-cols-[minmax(240px,1fr)_auto] lg:items-center"><label className="relative min-w-0"><span className="sr-only">Search pipeline</span><Search className="pointer-events-none absolute left-3.5 top-1/2 size-4 -translate-y-1/2 text-[var(--admin-muted)]" /><input value={state.search} onChange={(event) => patchState({ search: event.target.value })} placeholder="Search company, person, or email" className="min-h-11 w-full rounded-xl border border-[var(--admin-border)] bg-[var(--admin-surface-subtle)] pl-10 pr-3.5 text-sm outline-none focus:border-[var(--admin-ink)] focus:ring-2 focus:ring-[var(--admin-ink)]/10" /></label><div className="flex flex-wrap items-center gap-2"><Select value={state.stage} label="Filter by stage" onChange={(value) => patchState({ stage: value as PipelineViewState["stage"] })}><option value="all">All stages</option>{REVENUE_STAGES.map((stage) => <option key={stage} value={stage}>{REVENUE_STAGE_META[stage].label}</option>)}</Select><Select value={state.owner} label="Filter by owner" onChange={(owner) => patchState({ owner })}><option value="all">All owners</option>{owners.map((owner) => <option key={owner} value={owner}>{owner === "unassigned" ? "Unassigned" : owner}</option>)}</Select><ToolButton label="Customize" icon={Settings2} onClick={() => setDialog("customize")} /><ToolButton label="Save view" icon={BookmarkPlus} onClick={() => setDialog("save")} /><div className="flex rounded-xl p-1 shadow-[var(--admin-shadow-border)]" role="group" aria-label="Pipeline layout"><IconButton label="Board view" active={state.layout === "board"} onClick={() => patchState({ layout: "board" })} icon={Columns3} /><IconButton label="List view" active={state.layout === "list"} onClick={() => patchState({ layout: "list" })} icon={List} /></div></div></div>
        {state.layout === "board" ? <Board groups={groups} state={state} saving={saving} updateStage={updateStage} /> : <ListView items={shown} state={state} saving={saving} updateStage={updateStage} />}
      </AdminSurface>
    </>}

    <AdminDialog open={dialog === "customize"} onClose={() => setDialog(null)} title="Customize pipeline view" labelledBy="customize-pipeline-title" maxWidth="md"><div className="admin-dialog-surface w-full rounded-[24px] bg-[var(--admin-surface)] p-6"><DialogHead id="customize-pipeline-title" eyebrow="Pipeline view" title="Customize your workspace" description="Choose the information and ordering that help you make the next decision." close={() => setDialog(null)} /><fieldset className="mt-6"><legend className="admin-eyebrow">Visible fields</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{PIPELINE_VISIBLE_FIELDS.map((field) => { const selected = has(state, field.id); return <button key={field.id} type="button" aria-pressed={selected} onClick={() => patchState({ visibleFields: selected ? state.visibleFields.filter((item) => item !== field.id) : [...state.visibleFields, field.id] })} className={cn("flex min-h-11 items-center justify-between rounded-xl px-3.5 text-xs font-semibold shadow-[var(--admin-shadow-border)] active:scale-[0.96]", selected ? "bg-black/[0.045] dark:bg-white/[0.06]" : "text-[var(--admin-muted)]")}><span>{field.label}</span>{selected && <Check className="size-4" />}</button>; })}</div></fieldset><div className="mt-5 grid gap-4 sm:grid-cols-2"><SelectBlock label="Sort by" value={state.sortField} onChange={(sortField) => patchState({ sortField: sortField as PipelineViewState["sortField"] })}><option value="next_action_at">Next action</option><option value="created_at">Created date</option><option value="estimated_value">Value</option><option value="name">Name</option></SelectBlock><SelectBlock label="Direction" value={state.sortDirection} onChange={(sortDirection) => patchState({ sortDirection: sortDirection as PipelineViewState["sortDirection"] })}><option value="asc">Ascending</option><option value="desc">Descending</option></SelectBlock></div><div className="mt-6 flex justify-between"><button type="button" onClick={() => { setState(DEFAULT_PIPELINE_VIEW); setActiveSaved(null); }} className="min-h-11 rounded-xl px-3 text-xs font-semibold text-[var(--admin-muted)] active:scale-[0.96]">Reset defaults</button><button type="button" onClick={() => setDialog(null)} className="min-h-11 rounded-xl bg-[var(--admin-ink)] px-4 text-xs font-semibold text-[var(--admin-surface)] active:scale-[0.96]">Done</button></div></div></AdminDialog>
    <AdminDialog open={dialog === "save"} onClose={() => setDialog(null)} title="Save pipeline view" labelledBy="save-pipeline-title" maxWidth="sm"><form onSubmit={storeView} className="admin-dialog-surface w-full rounded-[24px] bg-[var(--admin-surface)] p-6"><DialogHead id="save-pipeline-title" eyebrow="Saved view" title="Name this workspace" description="Your filters, fields, sort, and layout will be available on this device." close={() => setDialog(null)} /><label className="mt-6 block text-xs font-semibold">View name<input autoFocus required maxLength={60} value={viewName} onChange={(event) => setViewName(event.target.value)} placeholder="Founder weekly review" className="mt-1.5 min-h-11 w-full rounded-xl border border-[var(--admin-border)] bg-[var(--admin-surface-subtle)] px-3.5 text-sm font-normal outline-none" /></label><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setDialog(null)} className="min-h-11 px-4 text-xs font-semibold text-[var(--admin-muted)]">Cancel</button><button type="submit" className="min-h-11 rounded-xl bg-[var(--admin-ink)] px-4 text-xs font-semibold text-[var(--admin-surface)] active:scale-[0.96]">Save view</button></div></form></AdminDialog>
    <AdminDialog open={dialog === "create"} onClose={() => setDialog(null)} title="New opportunity" labelledBy="new-opportunity-title" maxWidth="md"><form onSubmit={create} className="admin-dialog-surface max-h-[92dvh] w-full overflow-y-auto rounded-[24px] bg-[var(--admin-surface)] p-6"><DialogHead id="new-opportunity-title" eyebrow="Pipeline" title="New opportunity" description="Creates or resolves the contact and company before opening the opportunity." close={() => setDialog(null)} /><div className="mt-6 grid gap-4 sm:grid-cols-2">{[["name", "Contact name", "text", true], ["email", "Email", "email", true], ["companyName", "Company", "text"], ["website", "Website", "text"], ["estimatedValue", "Estimated value", "number"], ["nextActionAt", "Next action date", "datetime-local"]].map(([name, label, type, required]) => <label key={String(name)} className="text-xs font-semibold">{String(label)}<input name={String(name)} type={String(type)} required={Boolean(required)} min={type === "number" ? "0" : undefined} className="mt-1.5 min-h-11 w-full rounded-xl border border-[var(--admin-border)] bg-[var(--admin-surface-subtle)] px-3.5 text-sm font-normal outline-none" /></label>)}</div><label className="mt-4 block text-xs font-semibold">Next action<input name="nextAction" placeholder="Send audit follow-up" className="mt-1.5 min-h-11 w-full rounded-xl border border-[var(--admin-border)] bg-[var(--admin-surface-subtle)] px-3.5 text-sm font-normal" /></label><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setDialog(null)} className="min-h-11 px-4 text-xs font-semibold text-[var(--admin-muted)]">Cancel</button><button type="submit" disabled={saving} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[var(--admin-ink)] px-4 text-xs font-semibold text-[var(--admin-surface)] disabled:opacity-50">{saving && <Loader2 className="size-4 animate-spin" />} Create opportunity</button></div></form></AdminDialog>
  </div>;
}

function Select({ value, label, onChange, children }: { value: string; label: string; onChange: (value: string) => void; children: React.ReactNode }) { return <select value={value} aria-label={label} onChange={(event) => onChange(event.target.value)} className="min-h-11 min-w-0 flex-1 rounded-xl border border-[var(--admin-border)] bg-[var(--admin-surface)] px-3 text-xs font-semibold outline-none sm:flex-none">{children}</select>; }
function SelectBlock({ label, value, onChange, children }: { label: string; value: string; onChange: (value: string) => void; children: React.ReactNode }) { return <label className="text-xs font-semibold">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1.5 min-h-11 w-full rounded-xl border border-[var(--admin-border)] bg-[var(--admin-surface-subtle)] px-3.5 text-sm outline-none">{children}</select></label>; }
function ToolButton({ label, icon: Icon, onClick }: { label: string; icon: typeof Settings2; onClick: () => void }) { return <button type="button" onClick={onClick} className="inline-flex min-h-11 items-center gap-2 rounded-xl px-3 text-xs font-semibold text-[var(--admin-muted)] shadow-[var(--admin-shadow-border)] hover:text-[var(--admin-ink)] active:scale-[0.96]"><Icon className="size-4" />{label}</button>; }
function IconButton({ label, active, onClick, icon: Icon }: { label: string; active: boolean; onClick: () => void; icon: typeof List }) { return <button type="button" aria-label={label} aria-pressed={active} onClick={onClick} className={cn("grid size-9 place-items-center rounded-lg active:scale-[0.96]", active ? "bg-[var(--admin-ink)] text-[var(--admin-surface)]" : "text-[var(--admin-muted)]")}><Icon className="size-4" /></button>; }
function DialogHead({ id, eyebrow, title, description, close }: { id: string; eyebrow: string; title: string; description: string; close: () => void }) { return <div className="flex items-start justify-between gap-4"><div><p className="admin-eyebrow">{eyebrow}</p><h2 id={id} className="mt-1 text-balance text-xl font-semibold tracking-[-0.03em]">{title}</h2><p className="admin-copy mt-1 text-pretty text-sm">{description}</p></div><button type="button" onClick={close} aria-label="Close" className="grid size-11 shrink-0 place-items-center rounded-xl text-[var(--admin-muted)] active:scale-[0.96]"><X className="size-4" /></button></div>; }

function StageSelect({ item, saving, updateStage }: { item: Opportunity; saving: boolean; updateStage: (item: Opportunity, stage: RevenueStage) => Promise<void> }) { const stage = item.canonical_stage ?? "new"; return <select aria-label={`Stage for ${item.name || item.company?.name || "opportunity"}`} value={stage} disabled={saving} onChange={(event) => void updateStage(item, event.target.value as RevenueStage)} className={cn("min-h-10 max-w-[150px] rounded-xl border-0 px-3 text-xs font-semibold outline-none ring-1 ring-inset ring-black/5 focus:ring-2 disabled:opacity-50 dark:ring-white/10", tones[stage])}>{REVENUE_STAGES.map((value) => <option key={value} value={value}>{REVENUE_STAGE_META[value].label}</option>)}</select>; }
function Card({ item, state, saving, updateStage }: { item: Opportunity; state: PipelineViewState; saving: boolean; updateStage: (item: Opportunity, stage: RevenueStage) => Promise<void> }) { return <article data-opportunity-id={item.id} className="rounded-2xl bg-[var(--admin-surface)] p-4 shadow-[var(--admin-shadow-border)] transition-[box-shadow,transform] duration-150 hover:-translate-y-px hover:shadow-[var(--admin-shadow-border-hover)] motion-reduce:transform-none"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><Link href={`/admin/pipeline/${item.id}`} className="inline-flex min-h-10 max-w-full items-start gap-1.5 rounded-lg py-1 text-sm font-semibold hover:opacity-70 active:scale-[0.96]"><span className="truncate">{item.name || item.company?.name || "Untitled opportunity"}</span><ArrowUpRight className="mt-0.5 size-3.5 shrink-0" /></Link>{has(state, "contact") && <p className="admin-copy truncate text-xs">{item.company?.name || item.contact?.full_name || item.email || "Identity details pending"}</p>}</div>{has(state, "value") && <span className="shrink-0 font-mono text-xs font-semibold tabular-nums">{money(item.estimated_value)}</span>}</div>{has(state, "next_action") && <div className="mt-4 rounded-xl bg-[var(--admin-surface-subtle)] px-3 py-2.5"><p className="admin-eyebrow">Next action</p><p className="mt-1 line-clamp-2 text-xs leading-5">{item.next_action || "Set a specific next action"}</p><p className="admin-copy mt-1 text-[10px] tabular-nums">{shortDate(item.next_action_at)}{item.next_meeting_at ? ` · Meeting ${shortDate(item.next_meeting_at)}` : ""}</p></div>}<div className="mt-3 flex items-center justify-between gap-3"><div className="min-w-0">{has(state, "source") && <p className="truncate text-[10px] font-semibold uppercase tracking-[0.08em] text-[var(--admin-muted)]">{item.source || "Unknown source"}</p>}{has(state, "owner") && <p className="mt-1 truncate text-[10px] text-[var(--admin-muted)]">{item.owner_email || "Unassigned"}</p>}</div><StageSelect item={item} saving={saving} updateStage={updateStage} /></div></article>; }
function Board({ groups, state, saving, updateStage }: { groups: { stage: RevenueStage; opportunities: Opportunity[]; total: number }[]; state: PipelineViewState; saving: boolean; updateStage: (item: Opportunity, stage: RevenueStage) => Promise<void> }) { return <div aria-label="Canonical opportunity stage board" className="w-full min-w-0 snap-x snap-mandatory overflow-x-auto border-t border-[var(--admin-border)] bg-black/[0.012] p-4 dark:bg-white/[0.012] sm:p-5"><div className="flex min-w-max items-start gap-3">{groups.map((group) => <section key={group.stage} aria-labelledby={`pipeline-stage-${group.stage}`} className="w-[286px] shrink-0 snap-start"><div className="mb-3 flex min-h-11 items-center justify-between gap-3 px-1"><div className="flex items-center gap-2"><h2 id={`pipeline-stage-${group.stage}`} className="text-xs font-semibold">{REVENUE_STAGE_META[group.stage].label}</h2><span className="font-mono text-[9px] tabular-nums text-[var(--admin-muted)]">{group.opportunities.length}</span></div>{has(state, "value") && <span className="font-mono text-[10px] tabular-nums text-[var(--admin-muted)]">{money(group.total)}</span>}</div><div className="space-y-2.5">{group.opportunities.map((item) => <Card key={item.id} item={item} state={state} saving={saving} updateStage={updateStage} />)}{!group.opportunities.length && <div className="grid min-h-28 place-items-center rounded-2xl border border-dashed border-[var(--admin-border)] px-4 text-center"><p className="admin-copy text-xs">No opportunities in this stage.</p></div>}</div></section>)}</div></div>; }
function ListView({ items, state, saving, updateStage }: { items: Opportunity[]; state: PipelineViewState; saving: boolean; updateStage: (item: Opportunity, stage: RevenueStage) => Promise<void> }) { return <div className="border-t border-[var(--admin-border)]"><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-black/[0.018] font-mono text-[9px] uppercase tracking-[0.12em] text-[var(--admin-muted)]"><tr><th className="px-5 py-3.5">Opportunity</th>{has(state, "contact") && <th>Contact</th>}{has(state, "source") && <th>Source</th>}{has(state, "value") && <th className="text-right">Value</th>}{has(state, "next_action") && <th>Next action</th>}{has(state, "owner") && <th>Owner</th>}<th className="px-5">Stage</th></tr></thead><tbody className="divide-y divide-[var(--admin-border)]">{items.map((item) => <tr key={item.id} data-opportunity-id={item.id}><td className="px-5 py-4"><Link href={`/admin/pipeline/${item.id}`} className="inline-flex min-h-10 items-center gap-1.5 font-semibold hover:opacity-70">{item.name || item.company?.name || "Untitled"}<ArrowUpRight className="size-3.5" /></Link><p className="admin-copy text-xs">{item.company?.domain || "Company details pending"}</p></td>{has(state, "contact") && <td className="px-4">{item.contact?.full_name || item.email || "Unknown"}</td>}{has(state, "source") && <td className="px-4 text-xs text-[var(--admin-muted)]">{item.source || "Unknown"}</td>}{has(state, "value") && <td className="px-4 text-right font-mono tabular-nums">{money(item.estimated_value)}</td>}{has(state, "next_action") && <td className="max-w-[240px] px-4"><p className="truncate text-xs">{item.next_action || "Set next action"}</p><p className="admin-copy text-[10px]">{shortDate(item.next_action_at)}</p></td>}{has(state, "owner") && <td className="max-w-[180px] truncate px-4 text-xs">{item.owner_email || "Unassigned"}</td>}<td className="px-5"><StageSelect item={item} saving={saving} updateStage={updateStage} /></td></tr>)}{!items.length && <tr><td colSpan={7} className="px-6 py-16 text-center"><Empty /></td></tr>}</tbody></table></div><div className="grid gap-3 p-4 md:hidden">{items.map((item) => <Card key={item.id} item={item} state={state} saving={saving} updateStage={updateStage} />)}{!items.length && <Empty />}</div></div>; }
function Empty() { return <div className="py-8 text-center"><Target className="mx-auto size-5 text-[var(--admin-muted)]" /><p className="mt-3 text-sm font-semibold">No matching opportunities</p><p className="admin-copy mt-1 text-xs">Adjust the view or create the first opportunity.</p></div>; }
